// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#define INSTANCE_CULLING_PRESERVE_INSTANCE_ORDER_BIT_MASK 1U
#define INSTANCE_CULLING_DYNAMIC_INSTANCE_DATA_OFFSET_BIT_MASK 2U

#define INSTANCE_CULLING_PAYLOAD_NUM_COMMON_BITS 2U
