// Copyright Epic Games, Inc. All Rights Reserved.

#include "Verification/MetaHumanCharacterValidation.h"

#include "Verification/MetaHumanVerificationRuleCollection.h"
#include "Verification/VerifyObjectValid.h"
#include "Verification/VerifyMetaHumanGroom.h"
#include "Verification/VerifyMetaHumanSkeletalClothing.h"
#include "Verification/VerifyMetaHumanOutfitClothing.h"
#include "Verification/MetaHumanCharacterTypesVerification.h"

#include "MetaHumanAssetReport.h"
#include "MetaHumanCharacter.h"
#include "MetaHumanCollection.h"
#include "MetaHumanCharacterInstance.h"
#include "MetaHumanWardrobeItem.h"
#include "MetaHumanCharacterPaletteEditorModule.h"
#include "MetaHumanCharacterEditorSettings.h"

#include "Misc/UObjectToken.h"
#include "GroomBindingAsset.h"
#include "ChaosOutfitAsset/OutfitAsset.h"
#include "Engine/SkeletalMesh.h"
#include "Algo/AnyOf.h"

#define LOCTEXT_NAMESPACE "MetaHumanCharacterValidation"

bool UMetaHumanCharacterValidationContext::ValidateWardrobeItem(const class UMetaHumanWardrobeItem* InWardrobeItem)
{
	FMetaHumanVerificationOptions VerificationOptions;
	VerificationOptions.bVerbose = false;
	VerificationOptions.bTreatWarningsAsErrors = false;

	// This is a check used for packaging MetaHumans and its not needed for compatibility tests
	// Extension verifications are going to be manually applied here
	VerificationOptions.bVerifyPackagingRules = false;

	TStrongObjectPtr<UMetaHumanAssetReport> AssetReport{ NewObject<UMetaHumanAssetReport>() };
	AssetReport->SetSilent(bSilent);

	UObject* PrincipalAsset = InWardrobeItem->PrincipalAsset.LoadSynchronous();

	if (IsValid(PrincipalAsset))
	{
		// Grooms and Clothing extensions are part of the mhpkg validation, so run them manually here
		// TODO: Ideally this would be handled automatically by the report system, but in the current version, the
		//		extensions are verifying all wardrobe items in a path which is not what this validation should do
		//		so this in combination with bVerifyPackagingRules will skip this verification and should be addressed
		UMetaHumanCharacterTypesVerification* ExtensionVerification = NewObject<UMetaHumanCharacterTypesVerification>();
		if (PrincipalAsset->IsA<USkeletalMesh>())
		{
			ExtensionVerification->VerifySkelMeshClothingWardrobeItem(InWardrobeItem, PrincipalAsset, AssetReport.Get());
		}
		else if (PrincipalAsset->IsA<UGroomBindingAsset>())
		{
			ExtensionVerification->VerifyGroomWardrobeItem(InWardrobeItem, PrincipalAsset, AssetReport.Get());
		}
	}

	UMetaHumanVerificationRuleCollection* VerificationCollection = NewObject<UMetaHumanVerificationRuleCollection>();
	VerificationCollection->AddVerificationRule(NewObject<UVerifyObjectValid>());
	VerificationCollection->AddVerificationRule(NewObject<UVerifyMetaHumanGroom>());
	VerificationCollection->AddVerificationRule(NewObject<UVerifyMetaHumanOutfitClothing>());
	VerificationCollection->AddVerificationRule(NewObject<UVerifyMetaHumanSkeletalClothing>());

	VerificationCollection->ApplyAllRules(PrincipalAsset, AssetReport.Get(), VerificationOptions);

	const EMetaHumanOperationResult ReportResult = AssetReport->GetReportResult();

	if (ReportResult == EMetaHumanOperationResult::Failure)
	{
		if (ObjectBeingValidated != InWardrobeItem)
		{
			TSharedRef<FTokenizedMessage> BeginMessage = AddMessage(EMessageSeverity::Info);
			BeginMessage->SetIdentifier(InWardrobeItem->GetFName());
			BeginMessage->AddText(LOCTEXT("BeginWardrobeItemValidation", "Validation report for Wardrobe Item"));
			BeginMessage->AddToken(FUObjectToken::Create(InWardrobeItem));
		}

		// Adds a reference to the wardrobe item as a prefix token in each message generated by the report, in case there are errors
		// the user gets a link pointing to the wardrobe item that failed validation
		const TArray<TSharedRef<FTokenizedMessage>> NewTokenizedMessages = AssetReport->GenerateTokenizedMessageReport();
		for (const TSharedRef<FTokenizedMessage>& TokenizedMessage : NewTokenizedMessages)
		{
			// Transfer the messages from the report to the validation context so they can be displayed when the report is done
			TSharedRef<FTokenizedMessage> NewMessage = AddMessage(TokenizedMessage->GetSeverity());
			NewMessage->SetIdentifier(InWardrobeItem->GetFName());
			NewMessage->AddToken(FUObjectToken::Create(InWardrobeItem));

			const TArray<TSharedRef<IMessageToken>>& MessageTokens = TokenizedMessage->GetMessageTokens();
			for (const TSharedRef<IMessageToken>& Token : MessageTokens)
			{
				NewMessage->AddToken(Token);
			}
		}
	}

	return ReportResult == EMetaHumanOperationResult::Success;
}


UMetaHumanCharacterValidationContext* UMetaHumanCharacterValidationContext::BeginReport(const FBeginReportParams& InReportParams)
{
	UMetaHumanCharacterValidationContext* ValidationContext2 = NewObject<UMetaHumanCharacterValidationContext>();
	ValidationContext2->bSilent = InReportParams.bSilent;

	if (IsValid(InReportParams.ObjectToValidate))
	{
		TSharedRef<FTokenizedMessage> BeginMessage = ValidationContext2->AddMessage(EMessageSeverity::Info);
		ValidationContext2->ObjectBeingValidated = InReportParams.ObjectToValidate;

		// Add a title message to the report
		BeginMessage->SetIdentifier(InReportParams.ObjectToValidate->GetFName());
		BeginMessage->AddText(LOCTEXT("BeginValidationPrefix", "Validation report for"));
		BeginMessage->AddToken(FUObjectToken::Create(InReportParams.ObjectToValidate));
	}

	return ValidationContext2;
}

TSharedRef<FTokenizedMessage> UMetaHumanCharacterValidationContext::AddMessage(EMessageSeverity::Type InSeverity)
{
	return TokenizedMessages.Add_GetRef(FTokenizedMessage::Create(InSeverity));
}

const TArray<TSharedRef<FTokenizedMessage>>& UMetaHumanCharacterValidationContext::GetMessages() const
{
	return TokenizedMessages;
}

void UMetaHumanCharacterValidationContext::CancelReport()
{
	bCancelled = true;
}

void UMetaHumanCharacterValidationContext::EndReport()
{
	if (!bCancelled)
	{
		const bool bHasWarningsOrErrors = Algo::AnyOf(TokenizedMessages, [](const TSharedRef<FTokenizedMessage>& Message)
													  {
														  return Message->GetSeverity() < EMessageSeverity::Info;
													  });

		if (bHasWarningsOrErrors)
		{
			FMessageLog MessageLog(UE::MetaHuman::MessageLogName);
			MessageLog.AddMessages(TokenizedMessages);

			const UMetaHumanCharacterEditorSettings* Settings = GetDefault<UMetaHumanCharacterEditorSettings>();
			if (!Settings->bSuppressMessageLogWhenValidatingItems)
			{
				MessageLog.Open();
			}
		}
	}

	MarkAsGarbage();
}

#undef LOCTEXT_NAMESPACE
