// Copyright Epic Games, Inc. All Rights Reserved.

#include "CompositeActor.h"

#include "CompositeCoreSubsystem.h"
#include "CompositeModule.h"
#include "CompositeCoreSettings.h"
#include "CompositeRenderTargetPool.h"

#include "Components/CompositeShadowReflectionCatcherComponent.h"
#include "Components/CompositeViewProjectionComponent.h"
#include "Layers/CompositeLayerShadowReflection.h"
#include "Layers/CompositeLayerPlate.h"
#include "Layers/CompositeLayerMainRender.h"

#include "Algo/Rotate.h"
#include "Components/PrimitiveComponent.h"
#include "Camera/CameraActor.h"
#include "Camera/CameraComponent.h"
#include "EngineUtils.h"
#include "Engine/Engine.h"
#include "Engine/World.h"
#include "Engine/Texture.h"
#include "Kismet/GameplayStatics.h"
#include "Materials/MaterialInstanceDynamic.h"
#include "SceneView.h"
#include "UObject/FortniteMainBranchObjectVersion.h"
#include "UObject/UE5ReleaseStreamObjectVersion.h"
#include "UObject/ObjectSaveContext.h"
#include "UObject/UObjectIterator.h"

#if WITH_EDITOR
#include "LevelEditor.h"
#include "Modules/ModuleManager.h"
#include "Misc/TransactionObjectEvent.h"

/** The editor object. */
extern UNREALED_API class UEditorEngine* GEditor;
#endif

#include UE_INLINE_GENERATED_CPP_BY_NAME(CompositeActor)

DECLARE_CYCLE_STAT(TEXT("Composite - Actor Tick"), STAT_Composite_Actor_Tick, STATGROUP_Composite);
DECLARE_CYCLE_STAT(TEXT("Composite - Actor EndOfFrame Update"), STAT_Composite_Actor_EndOfFrameUpdate, STATGROUP_Composite);

namespace UE
{
	namespace Composite
	{
		/** Tag that will be added on every component generated by the composite actor. */
		const FLazyName DefaultCompositeTag = TEXT("Composite Generated Component");

		namespace Private
		{
			/** Convert the allowed view mode setting into a set of view mode indices. */
			inline TSet<EViewModeIndex> GetViewModeIndices(ECompositeAllowedViewModes InMode)
			{
				switch (InMode)
				{
				case ECompositeAllowedViewModes::Default:
					return { VMI_Lit, VMI_PathTracing, VMI_Unknown };
				case ECompositeAllowedViewModes::MediaProfileUnknown:
					return { VMI_Unknown };
				default:
					break;
				}

				return {};
			}

			/** Return solo layer from list. */
			TObjectPtr<UCompositeLayerBase> FindSoloLayer(TArrayView<const TObjectPtr<UCompositeLayerBase>> InLayers)
			{
				TObjectPtr<UCompositeLayerBase> SoloLayer;

				// Iterate backwards so that lower passes in the UI are executed first
				for (const TObjectPtr<UCompositeLayerBase>& Layer : InLayers)
				{
					if (!IsValid(Layer) || !Layer->IsEnabled())
					{
						continue;
					}

					if (Layer->bIsSolo)
					{
						SoloLayer = Layer;
					}
				}

				return SoloLayer;
			}

			/**
			* Convenience function to register layers in the traversal context, while returning proxies for each layer input.
			* 
			* Returns an index indicating the first proxy whose output can no longer be shared between post-processing locations.
			*/
			int32 RegisterLayers(UCompositeLayerBase::FTraversalContext& Context, TArrayView<const TObjectPtr<UCompositeLayerBase>> InLayers, FSceneRenderingBulkObjectAllocator& InFrameAllocator, TArray<FCompositeCorePassProxy*>& OutProxies)
			{
				int32 LastLayerIndex = INDEX_NONE;
				int32 BranchLayerIndex = INDEX_NONE;
				OutProxies.Reserve(InLayers.Num());

				for (const TObjectPtr<UCompositeLayerBase>& Layer : InLayers)
				{
					if (!IsValid(Layer) || !Layer->IsEnabled())
					{
						continue;
					}

					FCompositeCorePassProxy* OutProxy;
					if (Layer->GetProxy(Context, InFrameAllocator, OutProxy))
					{
						OutProxies.Add(OutProxy);
						Context.bIsFirstPass = false;

						const int32 ProxyIndex = OutProxies.Num() - 1;
						// If the pass needed scene textures specific to each post-processing location, its output
						// cannot be recyled in multiple locations. We therefore mark it as the "branch" layer.
						if (Context.bNeedsSceneTextures)
						{
							if (BranchLayerIndex == INDEX_NONE)
							{
								BranchLayerIndex = ProxyIndex;
							}
						}

						// Since merge passes handle color encodings & lens distortion, and
						// since SSR Input & tonemap differ in both regards, we must at least
						// run one merge pass for each location currently.
						LastLayerIndex = ProxyIndex;
					}
				}

				return (BranchLayerIndex != INDEX_NONE) ? BranchLayerIndex : LastLayerIndex;
			}

			/* Gather render work (per frame) given the current composite actor properties. */
			UE::CompositeCore::FRenderWork GatherFrameRenderWork(
				const ACompositeActor& InCompositeActor,
				const TMap<TWeakObjectPtr<const UCompositeLayerBase>, FSceneCaptureComponentArray>& InSceneCapturesPerLayer)
			{
				if (InCompositeActor.GetCompositeLayers().IsEmpty())
				{
					return {};
				}

				UE::CompositeCore::FRenderWork RenderWork;
				TArray<TObjectPtr<UCompositeLayerBase>> Layers;

				TObjectPtr<UCompositeLayerBase> SoloLayer = FindSoloLayer(InCompositeActor.GetCompositeLayers());
				if (IsValid(SoloLayer))
				{
					Layers.Add(SoloLayer);
				}
				else
				{
					Layers = InCompositeActor.GetCompositeLayers();
					// TODO: Remove once we have UI customization displaying layers in the correct bottom-up order
					Algo::Reverse(Layers);
				}

				TArray<FCompositeCorePassProxy*> LayerProxies;
				UCompositeLayerBase::FTraversalContext Context;
				Context.bIsSolo = (Layers.Num() == 1);

				const int32 BranchLayerIndex = RegisterLayers(Context, Layers, *RenderWork.FrameAllocator, LayerProxies);
				
				if (LayerProxies.IsEmpty())
				{
					// Early return when there is no actively rendering layer
					return {};
				}

				/**
				* Register pre-processing passes before SSR branch below to prevent duplicate work.
				* These passes only run once at the start of a frame (see ApplyPreprocessing call site in FCompositeCoreSceneViewExtension).
				*/
				RenderWork.PreprocessingPasses = Context.PreprocessingPasses;

				if (InCompositeActor.bEnableScreenSpaceReflections)
				{
					const int32 BranchSourceIndex = BranchLayerIndex - 1;

					TArray<FCompositeCorePassProxy*> BranchedLayerProxies;
					Context.bIsFirstPass = true;
					RegisterLayers(Context, Layers, *RenderWork.FrameAllocator, BranchedLayerProxies);

					// Trim all proxies before our branch index (for the tonemap location) to instead recycle previous work.
					if (BranchedLayerProxies.IsValidIndex(BranchLayerIndex))
					{
						BranchedLayerProxies.RemoveAt(0, BranchLayerIndex);
					}

					if (ensureMsgf(!BranchedLayerProxies.IsEmpty(), TEXT("Unexpected empty branch proxy array.")) && LayerProxies.IsValidIndex(BranchSourceIndex))
					{
						// This is where we connect to the previous SSR input work branch.
						// Input0 will be merged on top of Input1, the previous proxy's output.
						const int32 NumInputs = BranchedLayerProxies[0]->GetNumDeclaredInputs();
						BranchedLayerProxies[0]->GetDeclaredInput(NumInputs-1).Set<const FCompositeCorePassProxy*>(LayerProxies[BranchSourceIndex]);
					}

					RenderWork.FramePasses.Emplace(ISceneViewExtension::EPostProcessingPass::SSRInput, LayerProxies);
					RenderWork.FramePasses.Emplace(ISceneViewExtension::EPostProcessingPass::Tonemap, BranchedLayerProxies);
				}
				else
				{
					RenderWork.FramePasses.Emplace(ISceneViewExtension::EPostProcessingPass::Tonemap, LayerProxies);
				}

				RenderWork.ExternalInputs = Context.GetExternalTextures();

				switch (InCompositeActor.MainRenderOutput)
				{
				case ECompositeMainRenderOutputMode::FinalColorHDR:
					RenderWork.MainRenderMode = ESceneCaptureSource::SCS_FinalColorHDR;
					break;
				case ECompositeMainRenderOutputMode::FinalToneCurveHDR:
					RenderWork.MainRenderMode = ESceneCaptureSource::SCS_FinalToneCurveHDR;
					break;
				default:
					break;
				}
				
				RenderWork.AllowedViewModes = GetViewModeIndices(InCompositeActor.AllowedViewModes);

				// Currently, each layer may use at most 2 scene captures, so we reserve the maximum case.
				RenderWork.SceneCapturesUpdateQueue.Reserve(InSceneCapturesPerLayer.Num() * 2);

				for (const auto& Pair : InSceneCapturesPerLayer)
				{
					const TWeakObjectPtr<const UCompositeLayerBase>& Layer = Pair.Key;
					if (Layer.IsValid() && Layer->IsEnabled())
					{
						for (const TObjectPtr<UCompositeSceneCapture2DComponent>& SceneCapture : Pair.Value.Components)
						{
							RenderWork.SceneCapturesUpdateQueue.Add(SceneCapture.Get());
						}
					}
				}

				return RenderWork;
			}
		}
	}
}

ACompositeActor::ACompositeActor(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
	, ViewProjectionComponent{}
	, bIsActive{true}
	, bIsEnabled{true}
// TODO: Can we find the current viewport render resolution instead?
// View rects are only accessible from the render thread, but maybe there is an alternative.
// This isn't needed by custom render passes, only regular scene capture render targets...
	, RenderResolution{1920, 1080}
	, bEnableScreenSpaceReflections{true}
	, bOverridesViewUserFlags{true}
	, ViewUserFlags{1}
	, MainRenderOutput{ECompositeMainRenderOutputMode::Default}
	, AllowedViewModes{ECompositeAllowedViewModes::Default}
	, bIsModifyingAProperty{false}
{
	PrimaryActorTick.bCanEverTick = true;
	PrimaryActorTick.bTickEvenWhenPaused = true;
	PrimaryActorTick.TickGroup = TG_PostUpdateWork;
	PrimaryActorTick.bStartWithTickEnabled = true;
	bAllowTickBeforeBeginPlay = true;

	SetActorEnableCollision(false);

	RootComponent = CreateDefaultSubobject<USceneComponent>(USceneComponent::GetDefaultSceneRootVariableName());

	ViewProjectionComponent = CreateDefaultSubobject<UCompositeViewProjectionComponent>(TEXT("CameraViewProjectionComponent"));
	AddInstanceComponent(ViewProjectionComponent);
}

ACompositeActor::~ACompositeActor() = default;

void ACompositeActor::PostLoad()
{
	Super::PostLoad();

#if WITH_EDITORONLY_DATA
	/**
	* Refactored scene capture management.
	* Instead of polluting the actor with old data structures, we remove old components and rely on their recreation.
	*/
	const bool bHandleSceneCaptureRefactor = GetLinkerCustomVersion(FFortniteMainBranchObjectVersion::GUID) < FFortniteMainBranchObjectVersion::CompositeActorSceneCaptureRefactor;
	const bool bHandleDerivedSceneCaptureTypes = GetLinkerCustomVersion(FUE5ReleaseStreamObjectVersion::GUID) < FUE5ReleaseStreamObjectVersion::CompositePluginDerivedSceneCaptures;

	if (bHandleSceneCaptureRefactor || bHandleDerivedSceneCaptureTypes)
	{
		TArray<UActorComponent*> ActorComponents;
		GetComponents(ActorComponents);

		for (auto It = ActorComponents.CreateIterator(); It; ++It)
		{
			if (USceneCaptureComponent2D* CaptureComponent = Cast<USceneCaptureComponent2D>(*It))
			{
				bool bDestroyComponent = false;

				if (bHandleSceneCaptureRefactor && CaptureComponent->IsA<UCompositeShadowReflectionCatcherComponent>())
				{
					bDestroyComponent = true;
				}

				if (bHandleDerivedSceneCaptureTypes && (CaptureComponent->GetClass() == USceneCaptureComponent2D::StaticClass()))
				{
					bDestroyComponent = true;
				}

				if (bDestroyComponent)
				{
					RemoveInstanceComponent(CaptureComponent);
					CaptureComponent->UnregisterComponent();
					CaptureComponent->DestroyComponent();
				}
			}
		}
	}
#endif // WITH_EDITORONLY_DATA
}

void ACompositeActor::PostRegisterAllComponents()
{
	using namespace UE::Composite::Private;

	Super::PostRegisterAllComponents();

#if WITH_EDITOR
	if (IsTemplate() || bIsModifyingAProperty)
	{
		return;
	}
#endif

	if (IsRendering())
	{
		PropagateStateChange(true);
	}
}

void ACompositeActor::UnregisterAllComponents(bool bForReregister)
{
	using namespace UE::Composite::Private;

	Super::UnregisterAllComponents(bForReregister);

	if (bForReregister || bIsModifyingAProperty)
	{
		return;
	}
	
	// State removal is done without any conditions to prevent stale state
	PropagateStateChange(false);
}

void ACompositeActor::PostUnregisterAllComponents()
{
	Super::PostUnregisterAllComponents();
}

void ACompositeActor::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);

	SCOPE_CYCLE_COUNTER(STAT_Composite_Actor_Tick);

	if (!IsRendering())
	{
		return;
	}

	UCompositeCoreSubsystem* Subsystem = UWorld::GetSubsystem<UCompositeCoreSubsystem>(GetWorld());
	if (IsValid(Subsystem))
	{
		Subsystem->SetRenderWork(UE::Composite::Private::GatherFrameRenderWork(*this, SceneCapturesPerLayer));

		UE::CompositeCore::FBuiltInRenderPassOptions Options;
		if (bOverridesViewUserFlags)
		{
			Options.ViewUserFlagsOverride = ViewUserFlags;
		}
		Subsystem->SetBuiltInRenderPassOptions(Options);
	}
}

void ACompositeActor::Destroyed()
{
	Super::Destroyed();

	for (TObjectPtr<UCompositeLayerBase>& Layer : CompositeLayers)
	{
		// Note: We don't use IsValid(..) since destruction should proceed even if the actor is pending kill.
		if (Layer != nullptr)
		{
			Layer->OnRemoved(GetWorld());
		}
	}
}

#if WITH_EDITOR
void ACompositeActor::PreDuplicateFromRoot(FObjectDuplicationParameters& DupParams)
{
	Super::PreDuplicateFromRoot(DupParams);

	/**
	 * Whether DupParams.DuplicateMode == EDuplicateMode::PIE or otherwise,
	 * we release transient scene capture render targets (which are not instanced properties)
	 * to prevent their duplication. Allocation must instead come from the pool.
	 * 
	 * This is necessary since scene capture's TextureTarget property is not instanced.
	 */
	TInlineComponentArray<USceneCaptureComponent2D*> SceneCaptureComponents(this);
	for (USceneCaptureComponent2D* CaptureComponent : SceneCaptureComponents)
	{
		FCompositeRenderTargetPool& Pool = FCompositeRenderTargetPool::Get();

		if (Pool.IsAssignedTarget(CaptureComponent->TextureTarget))
		{
			Pool.ReleaseTarget(CaptureComponent->TextureTarget);
		}
	}
}

void ACompositeActor::PreEditChange(FProperty* PropertyAboutToChange)
{
	TOptional<TGuardValue<bool>> ModifyingPropertyGuard;
	if (!IsActorBeingDestroyed())
	{
		if ((GEditor && GEditor->bIsSimulatingInEditor && GetWorld() != nullptr) || ReregisterComponentsWhenModified())
		{
			if (PropertyAboutToChange)
			{
				ModifyingPropertyGuard.Emplace(bIsModifyingAProperty, true);
			}
		}
	}

	Super::PreEditChange(PropertyAboutToChange);

	if (PropertyAboutToChange && PropertyAboutToChange->GetFName() == GET_MEMBER_NAME_CHECKED(ThisClass, CompositeLayers))
	{
		PreEditCompositeLayers = CompositeLayers;
	}
}

void ACompositeActor::PostEditChangeChainProperty(struct FPropertyChangedChainEvent& PropertyChangedChainEvent)
{
	TGuardValue<bool> ModifyingPropertyGuard{ bIsModifyingAProperty, true };

	Super::PostEditChangeChainProperty(PropertyChangedChainEvent);

	const FName PropertyName = PropertyChangedChainEvent.GetPropertyName();

	if (PropertyName == GET_MEMBER_NAME_CHECKED(ThisClass, bIsActive))
	{
		SetActive(bIsActive);
	}
	else if (PropertyName == GET_MEMBER_NAME_CHECKED(ThisClass, bIsEnabled))
	{
		SetEnabled(bIsEnabled);
	}
	else if (PropertyName == GET_MEMBER_NAME_CHECKED(ThisClass, CompositeLayers))
	{
		// Verify that there isn't another container property node further down in the chain (so we don't respond to array change events from a different array!)
		bool bWasNestedContainerChanged = false;
		FEditPropertyChain::TDoubleLinkedListNode* Node = PropertyChangedChainEvent.PropertyChain.GetActiveNode()->GetNextNode();
		while (!bWasNestedContainerChanged && Node && Node->GetValue())
		{
			bWasNestedContainerChanged = Node->GetValue()->IsA<FArrayProperty>() || Node->GetValue()->IsA<FSetProperty>() || Node->GetValue()->IsA<FMapProperty>();
			Node = Node->GetNextNode();
		}

		if (!bWasNestedContainerChanged)
		{
			const int32 ArrayIndex = PropertyChangedChainEvent.GetArrayIndex(PropertyName.ToString());

			int32 MainRenderIndex = INDEX_NONE;
			
			for (int32 Index =0; Index < CompositeLayers.Num(); ++Index)
			{
				const TObjectPtr<UCompositeLayerBase>& Layer = CompositeLayers[Index];

				if (!IsValid(Layer) || !Layer->IsEnabled())
				{
					continue;
				}

				if (Layer->IsA(UCompositeLayerMainRender::StaticClass()))
				{
					MainRenderIndex = Index;
				}
			}

			for (UCompositeLayerBase* PreEditCompositeLayer : PreEditCompositeLayers)
			{
				// Note: We don't use IsValid(..) since destruction should proceed even if the actor is pending kill.
				if (PreEditCompositeLayer != nullptr)
				{
					if (!CompositeLayers.Contains(PreEditCompositeLayer))
					{
						PreEditCompositeLayer->OnRemoved(GetWorld());
					}
				}
			}

			PreEditCompositeLayers.Reset();

			if (PropertyChangedChainEvent.PropertyChain.Num() <= 1)
			{
				for (int32 Index = 0; Index < CompositeLayers.Num(); ++Index)
				{
					if (UCompositeLayerPlate* PlateLayer = Cast<UCompositeLayerPlate>(CompositeLayers[Index]))
					{
						// For user convenience when dragging layers, we disable the composite mesh pipeline if the plate layer runs after the main render.
						// TODO: Invert condition if/when traversal is done in the regular indexed order in the new UI.
						PlateLayer->SetPlateMode(Index > MainRenderIndex ? ECompositePlateMode::CompositeMesh : ECompositePlateMode::Texture);
					}
				}
			}
		}
	}
	else if (PropertyName == GET_MEMBER_NAME_CHECKED(ThisClass, Camera))
	{
		if (IsValid(ViewProjectionComponent))
		{
			ViewProjectionComponent->SetTargetComponent(Camera);
		}
	}
}

void ACompositeActor::PreEditUndo()
{
	Super::PreEditUndo();

	PreEditCompositeLayers = CompositeLayers;
}

void ACompositeActor::PostEditUndo()
{
	for (UCompositeLayerBase* PreEditCompositeLayer : PreEditCompositeLayers)
	{
		// Note: We don't use IsValid(..) since destruction should proceed even if the actor is pending kill.
		if (PreEditCompositeLayer != nullptr)
		{
			if (!CompositeLayers.Contains(PreEditCompositeLayer))
			{
				PreEditCompositeLayer->OnRemoved(GetWorld());
			}
		}
	}

	PreEditCompositeLayers.Reset();

	UWorld* World = GetWorld();

	// Deactivate the current actor if any other actor is already active
	// This can a occur when a previously active actor deletion is undone.
	if (IsValid(World) && IsActive())
	{
		for (TActorIterator<ACompositeActor> It(World); It; ++It)
		{
			ACompositeActor* OtherActor = *It;
			if ((OtherActor != this) && IsValid(OtherActor) && OtherActor->IsActive())
			{
				SetActive(false);
				break;
			}
		}
	}

	Super::PostEditUndo();
}

void ACompositeActor::PostTransacted(const FTransactionObjectEvent& TransactionEvent)
{
	Super::PostTransacted(TransactionEvent);

	if (TransactionEvent.GetEventType() == ETransactionObjectEventType::UndoRedo)
	{
		const FName RenderResolutionName = GET_MEMBER_NAME_CHECKED(ThisClass, RenderResolution);
		if (TransactionEvent.GetChangedProperties().Contains(RenderResolutionName))
		{
			/**
			* When a resolution change is undone, the previous render targets are deserialized & replaced.
			* This leaves previous assignments invalid so we make sure to return them to the pool.
			*/
			TInlineComponentArray<USceneCaptureComponent2D*> SceneCaptureComponents(this);
			for (USceneCaptureComponent2D* CaptureComponent : SceneCaptureComponents)
			{
				FCompositeRenderTargetPool::Get().ReleaseAssigneeTargets(CaptureComponent);
			}
		}
	}
}

void ACompositeActor::SetIsTemporarilyHiddenInEditor(bool bIsHidden)
{
	Super::SetIsTemporarilyHiddenInEditor(bIsHidden);

	PropagateStateChange(IsRendering());
}

bool ACompositeActor::ShouldTickIfViewportsOnly() const
{
	return true;
}
#endif

bool ACompositeActor::IsActive() const
{
	return bIsActive;
}

void ACompositeActor::SetActive(bool bInActive)
{
	bIsActive = bInActive;

	PropagateStateChange(IsRendering());

	// Deactivate all other composite actors
	const UWorld* World = GetWorld();

	if (bIsActive && IsValid(World))
	{
		for (TActorIterator<ACompositeActor> It(World); It; ++It)
		{
			if (*It != this)
			{
				It->bIsActive = false;
				It->PropagateStateChange(false);
			}
		}
	}

	// Update the view projection matrix sent to the material parameter collection when changing which actor is active.
	if (bIsActive && IsValid(ViewProjectionComponent))
	{
		ViewProjectionComponent->ForceUpdate();
	}
}

bool ACompositeActor::IsEnabled() const
{
	return bIsEnabled;
}

void ACompositeActor::SetEnabled(bool bInEnabled)
{
	bIsEnabled = bInEnabled;

	PropagateStateChange(IsRendering());
}

FComponentReference& ACompositeActor::GetCamera()
{
	return Camera;
}

void ACompositeActor::SetCamera(const FComponentReference& InComponentReference)
{
	Camera = InComponentReference;
	
	if (IsValid(ViewProjectionComponent))
	{
		ViewProjectionComponent->SetTargetComponent(Camera);
	}
}

TArray<UCompositeLayerBase*> ACompositeActor::GetCompositeLayers()
{
	return CompositeLayers;
}

const TArray<TObjectPtr<UCompositeLayerBase>>& ACompositeActor::GetCompositeLayers() const
{
	return CompositeLayers;
}

void ACompositeActor::SetCompositeLayers(TArray<UCompositeLayerBase*> InLayers)
{
	for (UCompositeLayerBase* PreviousLayer : CompositeLayers)
	{
		if (PreviousLayer != nullptr)
		{
			if (!InLayers.Contains(PreviousLayer))
			{
				PreviousLayer->OnRemoved(GetWorld());
			}
		}
	}

	CompositeLayers = MoveTemp(InLayers);
}

template<>
UCompositeSceneCapture2DComponent* ACompositeActor::FindOrCreateSceneCapture(const UCompositeLayerBase* InLayer, int32 InIndex, FName InBaseName)
{
	if (!ensureMsgf(InLayer, TEXT("Expected non-null composite layer.")))
	{
		return nullptr;
	}

	if (!ensure(InIndex >= 0))
	{
		return nullptr;
	}

	if (!SceneCapturesPerLayer.Contains(InLayer))
	{
		SceneCapturesPerLayer.Add(InLayer, FSceneCaptureComponentArray{});
	}

	TArray<TObjectPtr<UCompositeSceneCapture2DComponent>>& SceneCaptures = SceneCapturesPerLayer[InLayer].Components;

	if (SceneCaptures.IsValidIndex(InIndex) && IsValid(SceneCaptures[InIndex]))
	{
		return SceneCaptures[InIndex];
	}

	const FName UniqueName = MakeUniqueObjectName(this, UCompositeSceneCapture2DComponent::StaticClass(), InBaseName);
	UCompositeSceneCapture2DComponent* Component = NewObject<UCompositeSceneCapture2DComponent>(this, UniqueName, RF_Transactional);
	Component->SetupAttachment(RootComponent);
	Component->RegisterComponent();
	Component->ComponentTags.Add(UE::Composite::DefaultCompositeTag);
	AddInstanceComponent(Component);
	
	const int32 MinSize = InIndex + 1;
	if (SceneCaptures.Num() < MinSize)
	{
		SceneCaptures.SetNumZeroed(MinSize);
	}
	SceneCaptures[InIndex] = Component;

#if WITH_EDITOR
	FModuleManager::LoadModuleChecked<FLevelEditorModule>("LevelEditor").BroadcastComponentsEdited();
#endif

	return Component;
}

template<>
UCompositeShadowReflectionCatcherComponent* ACompositeActor::FindOrCreateSceneCapture(const UCompositeLayerBase* InLayer, int32 InIndex, FName InBaseName)
{
	if (!ensureMsgf(InLayer, TEXT("Expected non-null composite layer.")))
	{
		return nullptr;
	}

	if (!ensure(InIndex >= 0))
	{
		return nullptr;
	}

	if (!SceneCapturesPerLayer.Contains(InLayer))
	{
		SceneCapturesPerLayer.Add(InLayer, {});
	}

	TArray<TObjectPtr<UCompositeSceneCapture2DComponent>>& SceneCaptureArray = SceneCapturesPerLayer[InLayer].Components;

	if (SceneCaptureArray.IsValidIndex(InIndex))
	{
		return Cast<UCompositeShadowReflectionCatcherComponent>(SceneCaptureArray[InIndex]);
	}

	const FName UniqueName = MakeUniqueObjectName(this, UCompositeShadowReflectionCatcherComponent::StaticClass(), InBaseName);
	UCompositeShadowReflectionCatcherComponent* Component = NewObject<UCompositeShadowReflectionCatcherComponent>(this, UniqueName, RF_Transactional);
	Component->SetupAttachment(RootComponent);
	Component->RegisterComponent();
	Component->ComponentTags.Add(UE::Composite::DefaultCompositeTag);
	AddInstanceComponent(Component);

	const int32 MinSize = InIndex + 1;
	if (SceneCaptureArray.Num() < MinSize)
	{
		SceneCaptureArray.SetNumZeroed(MinSize);
	}
	SceneCaptureArray[InIndex] = Component;

#if WITH_EDITOR
	FModuleManager::LoadModuleChecked<FLevelEditorModule>("LevelEditor").BroadcastComponentsEdited();
#endif

	return Component;
}

void ACompositeActor::DestroySceneCaptures(const UCompositeLayerBase* InLayer)
{
	if (!ensureMsgf(InLayer, TEXT("Expected non-null composite layer.")))
	{
		return;
	}

	bool bComponentRemoved = false;

	FSceneCaptureComponentArray RemovedArray;
	if (SceneCapturesPerLayer.RemoveAndCopyValue(InLayer, RemovedArray))
	{
		for (TObjectPtr<UCompositeSceneCapture2DComponent>& RemovedComponent : RemovedArray.Components)
		{
			if (IsValid(RemovedComponent))
			{
				RemoveInstanceComponent(RemovedComponent);
				RemovedComponent->UnregisterComponent();
				RemovedComponent->DestroyComponent();

				bComponentRemoved = true;
			}
		}
	}

#if WITH_EDITOR
	if (bComponentRemoved)
	{
		FModuleManager::LoadModuleChecked<FLevelEditorModule>("LevelEditor").BroadcastComponentsEdited();
	}
#endif
}

bool ACompositeActor::IsRendering() const
{
	bool bIsRendering = IsEnabled() && IsActive();

#if WITH_EDITOR
	if (IsTemporarilyHiddenInEditor())
	{
		bIsRendering = false;
	}
#endif

	return bIsRendering;
}

void ACompositeActor::PostJoinConcertSession()
{
	SetActive(false);

	OnPostJoinMultiUserSession.Broadcast();
}

void ACompositeActor::PropagateStateChange(bool bApply)
{
	for (TObjectPtr<UCompositeLayerBase>& Layer : CompositeLayers)
	{
		if (IsValid(Layer))
		{
			Layer->OnRenderingStateChange(bApply);
		}
	}

	// Remove state case
	if (!bApply)
	{
		UCompositeCoreSubsystem* Subsystem = UWorld::GetSubsystem<UCompositeCoreSubsystem>(GetWorld());
		if (IsValid(Subsystem))
		{
			Subsystem->ResetRenderWork();
			Subsystem->ResetBuiltInRenderPassOptions();
		}
	}
}


