// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#if USE_USD_SDK

#include "CoreMinimal.h"

#include "USDGeomMeshConversion.h"

#include "UsdWrappers/SdfPath.h"
#include "UsdWrappers/UsdPrim.h"

#include "USDIncludesStart.h"
#include "pxr/pxr.h"
#include "USDIncludesEnd.h"

#include "Math/Transform.h"

namespace UsdToUnreal::NaniteAssemblyUtils
{
	enum class ENaniteAssemblyMeshType : uint32
	{
		/** The prim either does not have the root API schema or has an invalid meshType */
		None,
		/** Static Mesh Nanite assembly root */
		StaticMesh,
		/** Skeletal Mesh Nanite assembly root */
		SkeletalMesh
	};

	/**
	 * Nanite assembly static/skeletal meshes must be categorized as either a 'base' or a 'part'. Base meshes
	 * reference part meshes and instance them one or more times via Nanite assembly nodes. Note that Nanite
	 * assembly meshes cannot currently be nested, and so a mesh cannot be both a base and part mesh.
	*/
	enum class EMeshCategory : uint32
	{
		// No category determined for this mesh
		None,

		// This mesh is a base mesh. It will depend on one one more referenced part meshes.
		Base,

		// This mesh is a part mesh, used by one or more base meshes. 
		Part
	};

	/**
	 * Basic structure to hold information about the current pointinstancer, the current prototype
	 * path, and the corresponding prototype index, as it relates to an instance proxy mesh. A stack
	 * of these entries can be used to fully describe nested pointinstancer subtrees.
	 */
	struct FPrimPrototypeEntry
	{
		UE::FSdfPath PointInstancerPrimPath;

		// The active prototype of the above pointinstancer
		UE::FSdfPath PrototypePrimPath;

		// The index of the above prototype
		int32 PrototypeIndex;

		// The total number of prototypes used by the pointinstancer
		int32 PrototypeCount;
	};

	/**
	 * Mesh structure to hold assembly meshes.
	 */
	struct FMeshEntry
	{
		// The category of this mesh.
		const EMeshCategory Category = EMeshCategory::None;

		// The full instance proxy path of this mesh
		const UE::FSdfPath PrimPath;

		// For skeletal mesh parts, the path of the (possibly ancestor) prim with NaniteAssemblySkelBindingAPI
		// binding info applied (empty for static mesh parts)
		const UE::FSdfPath SkelBindingPath;

		// The transform stack for this mesh for the case of nested pointinstancers
		const TArray<FTransform> TransformStack;

		// The prototype stack for this mesh for the case of nested pointinstancers
		const TArray<FPrimPrototypeEntry> PrototypeStack;

		// The interchange node uid of this mesh.
		FString NodeUid;

		USDUTILITIES_API FMeshEntry(
			EMeshCategory Category,
			const UE::FSdfPath& PrimPath,
			const UE::FSdfPath& SkelBindingPath,
			const TArray<FTransform>& TransformStack,
			const TArray<FPrimPrototypeEntry>& PrototypeStack);

		USDUTILITIES_API void Print() const;
	};

	/**
	 * Structure to hold mapping information between source pointinstancer prototypes and their prims,
	 * and interchange uids used for the corresponding Nanite assembly parts.
	 */
	struct FPrototypesToPartsRemappingInfo
	{
		// The arrays of part mesh uids generated by the pointinstancers prototype meshes 
		TArray<TArray<FString>> PartUids;

		// Local space transforms needed to transform the parts into the correct space for the current
		// pointinstancer and prototype
		TArray<FTransform> LocalTransforms;

		// A table mapping original pointinstancer prototype indices into the corresponding range
		// of part uids in the PartUids array
		TMap<int32, FInt32Range> OriginalPrototypeIndexToNewPartRangeTable;

		// The original number of prototypes used by the originating pointinstancer
		int32 OriginalPrototypeCount = INDEX_NONE;

		/** Returns true if the part uids were remapped, false otherwise. Part meshes that have the identity
		  * transform do not require remapping. When all the parts in the assembly have the identity
		  * transform no remapping is required, and the original PartUid array can be used as-is.
		  */
		USDUTILITIES_API bool IsRemapped() const
		{
			return !OriginalPrototypeIndexToNewPartRangeTable.IsEmpty();
		}
	};

	/** 
	 * Structure to retain the needed data of a Nanite assembly USD subtree for later use during payload retrieval. 
	 * 
	 * This data should be created during translation and utilized during payload retrieval to generate the corresponding
	 * UE::Interchange::FNaniteAssemblyDescription representation of the data.
	 
	 * This data contains sufficient information about prototype meshes and their (potentially nested) hierarchies that 
	 * it's unnecessary to re-traverse the USD assembly subtree a second time when creating the payload data.
	 * 
	 * Prototype prim information such as paths and transforms is stored directly in the structure. Large pointinstancer
	 * arrays e.g. prototype indices, transforms, bone influences, are not stored. Computing these should be deferred 
	 * until payload generation.
	 */
	class FNaniteAssemblyTraversalResult
	{
	public:

		// The assembly mesh type (static or skeletal)
		const ENaniteAssemblyMeshType AssemblyMeshType;

		// Path of the prim with the NaniteAssemblyRootAPI schema applied
		const UE::FSdfPath AssemblyRootPrimPath;

	private:

		// Array of the USD meshes used as either base or parts of the assembly
		TArray<TSharedPtr<FMeshEntry>> Entries;

		// The mesh prim paths in this result
		TSet<UE::FSdfPath> EntryPaths;

	public:

		/** Construct for the given mesh type and assembly root path. */
		USDUTILITIES_API explicit FNaniteAssemblyTraversalResult(
			ENaniteAssemblyMeshType InMeshType,
			const UE::FSdfPath& InAssemblyRootPrimPath);

		USDUTILITIES_API bool AddEntry(const TSharedPtr<FMeshEntry>& Entry);

		/** returns true if the assembly this result represents is the given type, false otherwise. */
		USDUTILITIES_API bool IsMeshType(ENaniteAssemblyMeshType MeshType) const;

		/** Get the top-level pointinstancer paths (used for instancing parts) contained in this assembly. */
		USDUTILITIES_API TSet<UE::FSdfPath> GetTopLevelPointInstancerPaths() const;

		/** 
		 * Get the non-pointinstancer native-instanced part meshes for this assembly.
		 * 
		 * @param OutEntries                 Output array native-instanced part entries
		 * @param OutMeshUidToPartIndexTable Output table that maps mesh uids to the 
		 *                                   corresponding index in the OutPartUids array
		 * @param OutPartUids                Output array of arrays of part uids
		 */
		USDUTILITIES_API bool CheckAndGetNativeInstancedPartMeshEntries(
			TArray<TSharedPtr<FMeshEntry>>& OutEntries,
			TMap<FString, int32>& OutMeshUidToPartIndexTable,
			TArray<TArray<FString>>& OutPartUids) const;

		/**
		 * Get entries for the given pointinstancer arranged by prototype index.
		 *
		 * @param PointInstancerPrimPath         The pointinstancer in the assembly to query
		 * @param OutMeshEntriesByPrototypeIndex Output table that groups entries by their originating prototype index                
		 * @param OutPrototypeCount              The total number of prototypes defined by the pointinstancer
		 */
		USDUTILITIES_API bool CheckAndGetMeshEntriesByPrototypeIndex(
			const UE::FSdfPath& PointInstancerPrimPath, 
			TMap<int32, TArray<TSharedPtr<FMeshEntry>>>& OutMeshEntriesByPrototypeIndex, 
			int32& OutPrototypeCount) const;

		/**
		 * Get the remapped part information for the given top-level pointinstancer. 
		 *
		 * @param PointInstancerPrimPath The pointinstancer in the assembly to query
		 * @param IndexStartOffset       The index offset to apply to the generated mapping
		 * @param OutRemappingInfo       The output remapping info
		 */
		USDUTILITIES_API bool GetRemappedPartsForTopLevelPointInstancer(
			const UE::FUsdPrim& PointInstancerPrim, 
			int32 IndexStartOffset, 
			FPrototypesToPartsRemappingInfo& OutRemappingInfo) const;

		/** Return true if there are mesh entries for the given category, false otherwise */
		USDUTILITIES_API bool HasEntriesForCategory(EMeshCategory Category) const;

		/** Get all the entries for the given category (part or base mesh) */
		USDUTILITIES_API TArray<TSharedPtr<FMeshEntry>> GetEntriesForCategory(EMeshCategory Category) const;

		/** Get all the interchange mesh uids for the given category */
		USDUTILITIES_API TArray<FString> GetMeshUidsForCategory(EMeshCategory Category) const;

		/** Convert the given entries into an array of mesh uids */
		USDUTILITIES_API static TArray<FString> ConvertMeshEntryArrayToMeshUidArray(const TArray<TSharedPtr<FMeshEntry>>& Entries);
	};

	/** 
	 * Pointinstancer structure suitable for holding the regular pointinstancer properties (proto indices,
	 * transforms), as well as the additional joint binding data needed by skeletal mesh assemblies. Each
	 * pointinstancer instance will be translated into a Nanite assembly node.
	 * 
	 * Rather than the regular array of prototype paths, a remapping table is available that maps assembly
	 * part meshes back to the original pointinstancer prototypes. This is needed because multiple 
	 * pointinstancers can be combined into a single Nanite assembly mesh and so the indices need 
	 * rearranging accordingly.
	.*/
	struct FNaniteAssemblyPointInstancerData
	{
		TArray<int32> ProtoIndices;

		TArray<FTransform> Transforms;

		// Pointinstancer prototypes, assembly part arrays, and remapping ranges
		FPrototypesToPartsRemappingInfo ProtoRemappingInfo;

		// Joint binding indices for skeletal mesh assemblies (should be kept empty for static mesh assemblies)
		TArray<int32> JointIndices;

		// Joint binding weights for skeletal mesh assemblies (should be kept empty for static mesh assemblies)
		TArray<float> JointWeights;

		// Nanite assembly bindings support multiple joints/weights (again, empty for static mesh assemblies). 
		TArray<int32> NumInfluencesPerInstance;

		// Validity field, check this before attempting to access the data
		bool bIsValid = false;
	};

    /** Simple utility class to efficiently resolve Nanite assembly joint bindings for multiple prims. */
	class FJointBindingHelper
	{
		// Skeleton identifier, used for log messages only
		const FString SkelIdentifier;

		const TArray<FString> JointNames;

		const float Time = 0.f;

		TMap<FString, int32> JointIndexByJointNameTable;

	public:

		/** Initialize the helper with the given array of joint names. */
		USDUTILITIES_API FJointBindingHelper(const FString& InSkelIdentifier, const TArray<FString>& InJointNames, float InTime);

		/**
		 * Get the authored joint indices, weights and element size from the given prim. The prim must have
		 * the NaniteAssemblySkelBindingAPI schema applied.
		 */
		USDUTILITIES_API bool Get(
			const UE::FUsdPrim& Prim, 
			TArray<int32>& OutJointIndices, 
			TArray<float>& OutJointWeights, 
			int32& OutElementSize) const;
	};

	/**
	 * Get Nanite joint binding data from the given prim. The prim must have the NaniteAssemblySkelBindingAPI
	 * schema applied (the caller must check before calling this function). Regular and pointinstancer prims are
	 * supported.
	 *
	 * The given array of skeleton joint names is needed in order to convert the joint names supplied by the schema
	 * into indices relative to the meshes base skeleton.
	 *
	 * @param Prim            A prim with NaniteAssemblySkelBindingAPI applied (typically an xform or pointinstancer prim)
	 * @param SkelIdentifier  Used only for log messages.
	 * @param SkelJointNames  The array of joint names from the assembly base skeleton.
	 * @param OutJointIndices The joint binding indices, acquired via mandatory primvar
	 *                        'primvars:unreal:naniteAssembly:bindJoints'
	 * @param OutJointWeights The joint binding weights, as specified by the optional primvar
	 *                        'primvars:unreal:naniteAssembly:bindJointWeights'
	 * @param OutElementSize  The number of bindings per instance.
	 * 
	 * @param JointIndexByJointNameTable Optional pre-generated table to accelerate joint index lookups
	 *
	 * @return                True if binding data was successfully retrieved, false otherwise
	 */
	USDUTILITIES_API bool GetJointBindingData(
		const UE::FUsdPrim& Prim,
		const FString& SkelIdentifier,
		const TArray<FString>& SkelJointNames, 
		float Time, 
		TArray<int32>& OutJointIndices, 
		TArray<float>& OutJointWeights, 
		int32& OutElementSize,
		const TMap<FString, int32>* JointIndexByJointNameTable = nullptr);

	/**
	 * Gets the Nanite assembly mesh type token ('staticMesh' or 'skeletalMesh'). The prim must have the
	 * NaniteAssemblyRootAPI schema applied (caller must check before calling this function).
	 *
	 * @return The mesh type, or ENaniteAssemblyMeshType::None if the given prim was invalid or misconfigured.
	 */
	USDUTILITIES_API ENaniteAssemblyMeshType GetNaniteAssemblyMeshType(const UE::FUsdPrim& NaniteAssemblyRootPrim);

	/**
	 * Check whether or not NaniteAssemblyExternalRefAPI is applied to the given prim, and if so, sets the 
	 * output string to the value of the attribute 'unreal:naniteAssembly:meshAssetPath' (or an empty string 
	 * if the attribute does not exist or is unauthored).
	 *
	 * Note that this function always returns true if NaniteAssemblyExternalRefAPI is applied, even if the specified
	 * string is not a valid asset or package. Since hierarchy traversal should always halt when this schema is
	 * encountered, the caller should use the return value irrespective of the validity of the supplied asset reference
	 * string. Since pipelines are, in theory, free to modify the assembly references if they want, it isn't really
	 * possible for translators to verify ahead of time anyway.
	 *
	 * @param Prim        The prim to check
	 * @param OutAssetRef The specified user asset reference
	 * @return            True if NaniteAssemblyExternalRefAPI is applied, false otherwise
	 */
	USDUTILITIES_API bool GetExternalAssetReference(const UE::FUsdPrim& Prim, FString& OutAssetRef);

	/**
	 * Returns the base UsdSkelSkeleton prim for the given Nanite assembly root prim. Note that this function does
	 * not re-verify whether the NaniteAssemblyRootAPI schema is applied, or if the meshType attribute is set to
	 * "skeletalMesh". The caller must check before calling this function.
	 *
	 * @param NaniteAssemblyRootPrim The input prim
	 * @return                       A valid UsdSkelSkeleton prim on success, or an invalid prim if no skeleton could be found
	 */
	USDUTILITIES_API UE::FUsdPrim GetBaseSkeletonPrimForSkeletalMeshAssembly(const UE::FUsdPrim& NaniteAssemblyRootPrim);

	/**
	 * Gets the masked prototype indices for the given pointinstancer prim at the given time. 
	 * 
	 * @return true if the prototype indices were successfully acquired, false otherwise.
     */
	USDUTILITIES_API bool GetPointInstancerProtoIndices(const UE::FUsdPrim& PointInstancerPrim, float Time, TArray<int32>& OutProtoIndices);

	/**
	 * Gets the masked transforms multiplied by the given parent transform for the given pointinstancer prim at the given time.
     *
     * @return true if the transforms were successfully acquired, false otherwise.
     */
	USDUTILITIES_API bool GetPointInstancerTransforms(
		const UE::FUsdPrim& PointInstancerPrim,
		const FTransform& ParentTransform, 
		float Time, 
		TArray<FTransform>& OutTransforms);

	/**
	 * Gets the array of prototype paths for the given pointinstancer prim.
	 */
	USDUTILITIES_API TArray<UE::FSdfPath> GetPointInstancerPrototypePaths(const UE::FUsdPrim& PointInstancerPrim);

	/**
	 * High-level wrapper of most of the above functions that, if everything is valid, returns a structure containing 
	 * all the needed pointinstancer data to construct one or more instanced assembly parts.
     *
	 * @param PointInstancerPrim   The pointinstancer prim to process.
	 * @param Options              The current mesh options, e.g. current time coordinate.
	 * @param TraversalResult      The FNaniteAssemblyTraversalResult containing instance and prototype information.
	 * @param SkelIdentifier       The base skeleton name for this assembly  (used only for log messages).
	 * @param JointNames           Array of joint names extracted from the base skeleton.
	 * @param PartIndexStartOffset The offset to use when generating remapped prototype/part slots. 
	 * @return                     FNaniteAssemblyPointInstancerData instance, check the bIsValid member before using.
	 */
	USDUTILITIES_API FNaniteAssemblyPointInstancerData GetPointInstancerData(
		const UE::FUsdPrim& PointInstancerPrim,
		const UsdToUnreal::FUsdMeshConversionOptions& Options,
		const FNaniteAssemblyTraversalResult& TraversalResult,
		const FString& SkelIdentifier,
		const TArray<FString>& JointNames,
		int32 PartIndexStartOffset = 0);
}

#endif // #if USE_USD_SDK
