// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "Engine/BlueprintGeneratedClass.h"
#include "UObject/Package.h"
#include "ActorModifierCoreGeneratedClass.generated.h"

/** Blueprint modifier class generated by UActorModifierCoreBlueprint */
UCLASS(MinimalAPI)
class UActorModifierCoreGeneratedClass : public UBlueprintGeneratedClass
{
	GENERATED_BODY()
};
