// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

// Macros for encoding strings
#define VERSION_TEXT(x) TEXT(x)
#define VERSION_STRINGIFY_2(x) VERSION_TEXT(#x)
#define VERSION_STRINGIFY(x) VERSION_STRINGIFY_2(x)

#define BUILD_STORAGE_TOOL_APPNAME TEXT("BuildStorageTool-Source")

#ifdef BUILD_STORAGE_TOOL_PRERELEASE
#undef BUILD_STORAGE_TOOL_APPNAME
#define BUILD_STORAGE_TOOL_APPNAME TEXT("BuildStorageTool-PreRelease")
#endif

#ifdef BUILD_STORAGE_TOOL_RELEASE
#undef BUILD_STORAGE_TOOL_APPNAME
#define BUILD_STORAGE_TOOL_APPNAME TEXT("BuildStorageTool")
#endif

#ifndef BUILD_STORAGE_TOOL_CHANGELIST
#define BUILD_STORAGE_TOOL_CHANGELIST_STRING TEXT("NoCL")
#endif

#ifdef BUILD_STORAGE_TOOL_CHANGELIST
#define BUILD_STORAGE_TOOL_CHANGELIST_STRING TEXT("CL-") VERSION_STRINGIFY(BUILD_STORAGE_TOOL_CHANGELIST)
#endif

