// Copyright Epic Games, Inc. All Rights Reserved.
#include "AudioInsightsEditorDashboardFactory.h"

#include "Async/Async.h"
#include "AudioDevice.h"
#include "AudioDeviceManager.h"
#include "AudioInsightsDashboardAssetCommands.h"
#include "AudioInsightsEditorModule.h"
#include "AudioInsightsEditorSettings.h"
#include "AudioInsightsStyle.h"
#include "AudioInsightsTraceModule.h"
#include "Engine/World.h"
#include "Framework/Commands/UICommandList.h"
#include "Framework/Docking/LayoutService.h"
#include "Framework/Docking/TabManager.h"
#include "Framework/Notifications/NotificationManager.h"
#include "Internationalization/Text.h"
#include "IPropertyTypeCustomization.h"
#include "Templates/SharedPointer.h"
#include "Widgets/Input/SButton.h"
#include "Widgets/Input/SCheckBox.h"
#include "Widgets/Layout/SSeparator.h"
#include "Widgets/Notifications/SNotificationList.h"

#define LOCTEXT_NAMESPACE "AudioInsights"

namespace UE::Audio::Insights
{
	namespace EditorDashboardFactoryPrivate
	{
		static const FText ToolNameText = LOCTEXT("AudioDashboardEditor_ToolName_Text", "Audio Insights");

		static const FText PreviewDeviceText = LOCTEXT("AudioDashboardEditor_PreviewDevice_Text", "[Preview Audio]");

		static const FText MainMenuFileText = LOCTEXT("AudioDashboardEditor_MainMenu_File_Text", "File");
		static const FText MainMenuViewText = LOCTEXT("AudioDashboardEditor_MainMenu_View_Text", "View");

		static const FText FileCloseText = LOCTEXT("AudioDashboardEditor_File_Close_Text", "Close");
		static const FText FileCloseTooltipText = LOCTEXT("AudioDashboardEditor_File_Close_TooltipText", "Closes the Audio Insights dashboard.");

		static const FText ViewResetLayoutText = LOCTEXT("AudioDashboardEditor_View_ResetLayout_Text", "Reset Layout");

		static const FText OnlyTraceAudioChannelsTooltipText = LOCTEXT("AudioDashboardEditor_OnlyTraceAudioChannels_TooltipText", "Disable all non-command line trace channels apart from Audio, Audio Mixer and Bookmark when starting a live monitoring / live trace. This will reduce the file size of snapshots / trace sessions while using Audio Insights.");

		static const FText StartMonitoringText = LOCTEXT("AudioDashboardEditor_StartMonitoring_Text", "Start Monitoring");
		static const FText StartMonitoringTooltipText = LOCTEXT("AudioDashboardEditor_StartMonitoring_TooltipText", "Starts monitoring for audio trace data without saving the data to a .utrace file.");

		static const FText StopMonitoringText = LOCTEXT("AudioDashboardEditor_StopMonitoring_Text", "Monitoring...");
		static const FText StopMonitoringTooltipText = LOCTEXT("AudioDashboardEditor_StopMonitoring_TooltipText", "Stops the active monitoring session.");

		static const FText StartRecordingText = LOCTEXT("AudioDashboardEditor_StartRecording_Text", "Start Recording");
		static const FText StartRecordingTooltipText = LOCTEXT("AudioDashboardEditor_StartRecording_TooltipText", "Starts to record audio trace data saving it to a .utrace file.");

		static const FText StopRecordingText = LOCTEXT("AudioDashboardEditor_StopRecording_Text", "Recording...");
		static const FText StopRecordingTooltipText = LOCTEXT("AudioDashboardEditor_StopRecording_TooltipText", "Stops the currently active trace recording.");

		static const FText RecordingNotificationText = LOCTEXT("AudioDashboardEditor_RecordingButton_NotificationText", "Trace Started");
		static const FText RecordingNotificationSubText = LOCTEXT("AudioDashboardEditor_RecordingButton_NotificationSubText", "Trace is now active and saving to the following location (file or tracestore):\n");

		static const FText SaveSnapshotTooltipText = LOCTEXT("AudioDashboardEditor_SnapshotButton_TooltipText", "Saves a snapshot of the most recent trace data to a .utrace file. By default snapshots are limited to 32MB and can be accessed in Unreal Insights. To specify a custom snapshot size (in MB) launch the editor executable with the -tracetailmb=<size> option.");

		static const FText SaveSnapshotNotificationText = LOCTEXT("AudioDashboardEditor_SnapshotButton_NotificationText", "Audio Insights Snapshot saved.");
		static const FText SaveSnapshotNotificationSubText = LOCTEXT("AudioDashboardEditor_SnapshotButton_NotificationSubText", "A snapshot .utrace with the most recent events has been saved to your trace server.");

		static const FText SaveBookmarkTooltipText = LOCTEXT("AudioDashboardEditor_BookmarkButton_TooltipText", "Ctrl+M - Creates an 'Audio Insights' bookmark in the .utrace file generated by Save Snapshot or Trace at the timestamp the button was pressed.");

		static const FText BookmarkLabelText = LOCTEXT("AudioDashboardEditor_BookmarkLabelTitle_Text", "Audio Insights Bookmark");
		static const FText SaveBookmarkNotificationText = LOCTEXT("AudioDashboardEditor_BookmarkButton_NotificationText", "Audio Insights Bookmark created.");
		static const FText SaveBookmarkNotificationDirectTraceSubText = LOCTEXT("AudioDashboardEditor_BookmarkButton_NotificationSubText", "bookmark has been added to the Audio Insights Snapshot.");
		static const FText SaveBookmarkNotificationLiveTraceSubText = LOCTEXT("AudioDashboardEditor_BookmarkButton_LiveTrace_NotificationSubText", "bookmark has been added to the live .utrace file on your trace server.");

		static const FText WorldFilterText = LOCTEXT("AudioDashboardEditor_WorldFilter_Text", "World Filter:");
		static const FText WorldFilterTooltipText = LOCTEXT("AudioDashboardEditor_WorldFilter_TooltipText", "Select world(s) to monitor (worlds may share audio output).");
		
		void ShowNotification(const FText& InText, const FText& InSubText)
		{
			FNotificationInfo Info(InText);
			Info.SubText = InSubText;
			Info.bFireAndForget = true;
			Info.FadeOutDuration = 1.0f;
			Info.ExpireDuration = 4.0f;

			FSlateNotificationManager::Get().AddNotification(Info);
		}

		void ShowRecordingNotification()
		{
			FString TraceDestinationStr = FTraceAuxiliary::GetTraceDestinationString();
			if (TraceDestinationStr.IsEmpty())
			{
				TraceDestinationStr = TEXT("External Target");
			}
			
			ShowNotification(RecordingNotificationText, FText::Format(FText::FromString(TEXT("{0}{1}")), RecordingNotificationSubText, FText::FromString(TraceDestinationStr)));
		}

		FText GetDebugNameFromDeviceId(::Audio::FDeviceId InDeviceId)
		{
			FString WorldName;
			if (FAudioDeviceManager* DeviceManager = FAudioDeviceManager::Get())
			{
				TArray<UWorld*> DeviceWorlds = DeviceManager->GetWorldsUsingAudioDevice(InDeviceId);
				for (const UWorld* World : DeviceWorlds)
				{
					if (!WorldName.IsEmpty())
					{
						WorldName += TEXT(", ");
					}
					WorldName += World->GetDebugDisplayName();
				}
			}

			if (WorldName.IsEmpty())
			{
				return PreviewDeviceText;
			}

			return FText::FromString(WorldName);
		}

		// Helper class required to intercept OnKeyDown events
		class SAudioInsightsTabContents : public SVerticalBox
		{
		public:
			SLATE_BEGIN_ARGS(SAudioInsightsTabContents)
			{}

			SLATE_EVENT(FOnKeyDown, OnKeyDown)

			SLATE_END_ARGS()

			void Construct(const FArguments& InArgs)
			{
				OnKeyDownHandler = InArgs._OnKeyDown;

				SVerticalBox::Construct(SVerticalBox::FArguments());
			}

			virtual FReply OnKeyDown(const FGeometry& MyGeometry, const FKeyEvent& InKeyEvent) override
			{
				if (OnKeyDownHandler.IsBound())
				{
					return OnKeyDownHandler.Execute(MyGeometry, InKeyEvent);
				}

				return SVerticalBox::OnKeyDown(MyGeometry, InKeyEvent);
			}

			virtual bool SupportsKeyboardFocus() const override { return true; }

		private:
			FOnKeyDown OnKeyDownHandler;
		};
	} // namespace EditorDashboardFactoryPrivate

	void FEditorDashboardFactory::OnWorldRegisteredToAudioDevice(const UWorld* InWorld, ::Audio::FDeviceId InDeviceId)
	{
		if (InDeviceId != INDEX_NONE)
		{
			SetActiveDeviceId(InDeviceId);
		}

		RefreshDeviceSelector();
	}

	void FEditorDashboardFactory::OnWorldUnregisteredFromAudioDevice(const UWorld* InWorld, ::Audio::FDeviceId InDeviceId)
	{
		RefreshDeviceSelector();
	}

	void FEditorDashboardFactory::OnTraceStarted(FTraceAuxiliary::EConnectionType InTraceType, const FString& InTraceDestination)
	{
		IAudioInsightsTraceModule& TraceModule = FAudioInsightsEditorModule::GetChecked().GetTraceModule();

		// If we haven't started a trace, start the analysis with the currently running trace
		if (!TraceModule.IsAudioInsightsTrace())
		{
			TraceModule.StartTraceAnalysis(bOnlyTraceAudioChannels, ETraceMode::Recording);
			BookmarkIndex = 0;
		}
	}

	void FEditorDashboardFactory::CreateTraceBookmark()
	{
		using namespace EditorDashboardFactoryPrivate;

		IAudioInsightsTraceModule& TraceModule = FAudioInsightsEditorModule::GetChecked().GetTraceModule();

		if (TraceModule.IsTraceAnalysisActive())
		{
			TRACE_BOOKMARK(TEXT("%s %d"), *BookmarkLabelText.ToString(), BookmarkIndex);
			BookmarkIndex++;

			// Show floating notification
			FNotificationInfo Info(SaveBookmarkNotificationText);

			const FText SubText = TraceModule.IsTraceAnalysisActive() ? SaveBookmarkNotificationLiveTraceSubText : SaveBookmarkNotificationDirectTraceSubText;

			static const FTextFormat SubTextFormat = FTextFormat::FromString(TEXT("{0} {1} {2}"));
			Info.SubText = FText::Format(SubTextFormat, BookmarkLabelText, BookmarkIndex, SubText);

			Info.bFireAndForget = true;
			Info.FadeOutDuration = 1.0f;
			Info.ExpireDuration = 4.0f;

			FSlateNotificationManager::Get().AddNotification(Info);
		}
	}

	void FEditorDashboardFactory::OnDeviceCreated(::Audio::FDeviceId InDeviceId)
	{
		OnActiveAudioDeviceChanged.Broadcast();
	}

	void FEditorDashboardFactory::OnDeviceDestroyed(::Audio::FDeviceId InDeviceId)
	{
		if (ActiveDeviceId == InDeviceId)
		{
			if (FAudioDeviceManager* DeviceManager = FAudioDeviceManager::Get())
			{
				ActiveDeviceId = DeviceManager->GetMainAudioDeviceID();
			}
		}

		AudioDeviceIds.RemoveAll([InDeviceId](const TSharedPtr<::Audio::FDeviceId>& DeviceIdPtr)
		{
			return *DeviceIdPtr.Get() == InDeviceId;
		});

		if (AudioDeviceComboBox.IsValid())
		{
			AudioDeviceComboBox->RefreshOptions();
		}

		OnActiveAudioDeviceChanged.Broadcast();
	}

	void FEditorDashboardFactory::RefreshDeviceSelector()
	{
		if (FAudioDeviceManager* DeviceManager = FAudioDeviceManager::Get())
		{
			if (!DeviceManager->IsValidAudioDevice(ActiveDeviceId))
			{
				ActiveDeviceId = DeviceManager->GetMainAudioDeviceID();
			}
		}

		AudioDeviceIds.Empty();
		if (const FAudioDeviceManager* DeviceManager = FAudioDeviceManager::Get())
		{
			DeviceManager->IterateOverAllDevices([this, &DeviceManager](::Audio::FDeviceId DeviceId, const FAudioDevice* AudioDevice)
			{
				AudioDeviceIds.Add(MakeShared<::Audio::FDeviceId>(DeviceId));
			});
		}

		if (AudioDeviceComboBox.IsValid())
		{
			AudioDeviceComboBox->RefreshOptions();
		}
	}

	void FEditorDashboardFactory::ResetDelegates()
	{
		if (OnWorldRegisteredToAudioDeviceHandle.IsValid())
		{
			FAudioDeviceWorldDelegates::OnWorldRegisteredToAudioDevice.Remove(OnWorldRegisteredToAudioDeviceHandle);
			OnWorldRegisteredToAudioDeviceHandle.Reset();
		}

		if (OnWorldUnregisteredFromAudioDeviceHandle.IsValid())
		{
			FAudioDeviceWorldDelegates::OnWorldUnregisteredWithAudioDevice.Remove(OnWorldUnregisteredFromAudioDeviceHandle);
			OnWorldUnregisteredFromAudioDeviceHandle.Reset();
		}

		if (OnDeviceCreatedHandle.IsValid())
		{
			FAudioDeviceManagerDelegates::OnAudioDeviceCreated.Remove(OnDeviceCreatedHandle);
			OnDeviceCreatedHandle.Reset();
		}

		if (OnDeviceDestroyedHandle.IsValid())
		{
			FAudioDeviceManagerDelegates::OnAudioDeviceDestroyed.Remove(OnDeviceDestroyedHandle);
			OnDeviceDestroyedHandle.Reset();
		}

		if (OnTraceStartedHandle.IsValid())
		{
			FTraceAuxiliary::OnTraceStarted.Remove(OnTraceStartedHandle);
			OnTraceStartedHandle.Reset();
		}
	}

	void FEditorDashboardFactory::BindCommands()
	{
		CommandList = MakeShared<FUICommandList>();

		const FDashboardAssetCommands& Commands = FDashboardAssetCommands::Get();
		CommandList->MapAction(Commands.GetTraceBookmarkCommand(), FExecuteAction::CreateRaw(this, &FEditorDashboardFactory::CreateTraceBookmark));
	}

	::Audio::FDeviceId FEditorDashboardFactory::GetDeviceId() const
	{
		return ActiveDeviceId;
	}

	FEditorDashboardFactory::FEditorDashboardFactory()
	{
		FDashboardAssetCommands::Register();

		BindCommands();
	}

	FEditorDashboardFactory::~FEditorDashboardFactory()
	{
		FDashboardAssetCommands::Unregister();
	}

	TSharedRef<SDockTab> FEditorDashboardFactory::MakeDockTabWidget(const FSpawnTabArgs& Args)
	{
		using namespace EditorDashboardFactoryPrivate;

		const TSharedRef<SDockTab> DockTab = SNew(SDockTab)
			.Label(ToolNameText)
			.Clipping(EWidgetClipping::ClipToBounds)
			.TabRole(ETabRole::NomadTab);

		DashboardTabManager = FGlobalTabmanager::Get()->NewTabManager(DockTab);

		DashboardTabManager->SetOnPersistLayout(FTabManager::FOnPersistLayout::CreateStatic([](const TSharedRef<FTabManager::FLayout>& InLayout)
		{
			if (InLayout->GetPrimaryArea().Pin().IsValid())
			{
				FLayoutSaveRestore::SaveToConfig(GEditorLayoutIni, InLayout);
			}
		}));

		InitDelegates();

		RegisterTabSpawners();
		RefreshDeviceSelector();

		if (FAudioDeviceManager* DeviceManager = FAudioDeviceManager::Get())
		{
			SetActiveDeviceId(DeviceManager->GetActiveAudioDevice()->DeviceID);
		}

		if (!bIsLayoutReseting)
		{
			IAudioInsightsTraceModule& TraceModule = FAudioInsightsEditorModule::GetChecked().GetTraceModule();
			TraceModule.StartTraceAnalysis(bOnlyTraceAudioChannels, ETraceMode::Monitoring);
		}

		const TSharedRef<FTabManager::FLayout> TabLayout = LoadLayoutFromConfig();

		TSharedRef<SVerticalBox> TabContent = SNew(SAudioInsightsTabContents)
			.OnKeyDown_Lambda([this](const FGeometry& MyGeometry, const FKeyEvent& InKeyEvent)
			{
				return (CommandList && CommandList->ProcessCommandBindings(InKeyEvent)) ? FReply::Handled() : FReply::Unhandled();
			});

		TabContent->AddSlot().AutoHeight()[ MakeMenuBarWidget() ];
		TabContent->AddSlot().AutoHeight()[ MakeMainToolbarWidget() ];
		TabContent->AddSlot().AutoHeight()[ SNew(SBox).HeightOverride(4.0f) ];
		TabContent->AddSlot()[ DashboardTabManager->RestoreFrom(TabLayout, Args.GetOwnerWindow()).ToSharedRef() ];

		DockTab->SetContent(TabContent);

		DockTab->SetOnTabClosed(SDockTab::FOnTabClosedCallback::CreateLambda([this](TSharedRef<SDockTab> TabClosed)
		{
			// Stop trace when closing Audio Insights (only if we have started it, we don't want to stop external traces)
			IAudioInsightsTraceModule& TraceModule = FAudioInsightsEditorModule::GetChecked().GetTraceModule();

			if (TraceModule.IsTraceAnalysisActive() && TraceModule.IsAudioInsightsTrace() && !bIsLayoutReseting)
			{
				TraceModule.StopTraceAnalysis();
			}

			ResetDelegates();
			UnregisterTabSpawners();
			SaveLayoutToConfig();

			for (const auto& KVP : DashboardViewFactories)
			{
				if (TSharedPtr<SDockTab> DashboardTab = DashboardTabManager->FindExistingLiveTab(KVP.Key))
				{
					// Explicitly close each dashboard tab. This will give a chance for it to close any undocked sub-managed tabs of its own:
					DashboardTab->RequestCloseTab();
				}
			}

			DashboardTabManager->CloseAllAreas();

			DashboardTabManager.Reset();
			DashboardWorkspace.Reset();
		}));

		return DockTab;
	}

	TSharedRef<SWidget> FEditorDashboardFactory::MakeMenuBarWidget()
	{
		using namespace EditorDashboardFactoryPrivate;

		FMenuBarBuilder MenuBarBuilder = FMenuBarBuilder(TSharedPtr<FUICommandList>());

		MenuBarBuilder.AddPullDownMenu(
			MainMenuFileText,
			FText::GetEmpty(),
			FNewMenuDelegate::CreateLambda([this](FMenuBuilder& MenuBuilder)
			{
				MenuBuilder.AddMenuEntry(
					FileCloseText,
					FileCloseTooltipText,
					FSlateIcon(),
					FUIAction(FExecuteAction::CreateLambda([this]()
					{
						if (DashboardTabManager.IsValid())
						{
							if (TSharedPtr<SDockTab> OwnerTab = DashboardTabManager->GetOwnerTab())
							{
								OwnerTab->RequestCloseTab();
							}
						}
					}))
				);
			}),
			"File"
		);

		MenuBarBuilder.AddPullDownMenu(
			MainMenuViewText,
			FText::GetEmpty(),
			FNewMenuDelegate::CreateLambda([this](FMenuBuilder& MenuBuilder)
			{
				for (const auto& KVP : DashboardViewFactories)
				{
					const FName& FactoryName = KVP.Key;
					const TSharedPtr<IDashboardViewFactory>& Factory = KVP.Value;

					MenuBuilder.AddMenuEntry(
						Factory->GetDisplayName(),
						FText::GetEmpty(),
						Factory->GetIcon(),
						FUIAction(FExecuteAction::CreateLambda([this, FactoryName]()
						{
							if (DashboardTabManager.IsValid())
							{
								if (TSharedPtr<SDockTab> ViewportTab = DashboardTabManager->FindExistingLiveTab(FactoryName);
									!ViewportTab.IsValid())
								{
									DashboardTabManager->TryInvokeTab(FactoryName);

									if (TSharedPtr<SDockTab> InvokedOutputMeterTab = DashboardTabManager->TryInvokeTab(FactoryName);
										InvokedOutputMeterTab.IsValid() && DashboardViewFactories[FactoryName].IsValid())
									{
										if (const EDefaultDashboardTabStack DefaultTabStack = DashboardViewFactories[FactoryName]->GetDefaultTabStack();
											DefaultTabStack == EDefaultDashboardTabStack::AudioAnalyzerRack)
										{
											InvokedOutputMeterTab->SetParentDockTabStackTabWellHidden(true);
										}
									}
								}
								else
								{
									ViewportTab->RequestCloseTab();
								}
							}
						}),
						FCanExecuteAction(),
						FIsActionChecked::CreateLambda([&DashboardTabManager = DashboardTabManager, FactoryName]()
						{
							return DashboardTabManager.IsValid() ? DashboardTabManager->FindExistingLiveTab(FactoryName).IsValid() : false;
						})),
						NAME_None,
						EUserInterfaceActionType::Check
					);

					if (const EDefaultDashboardTabStack DefaultTabStack = DashboardViewFactories[FactoryName]->GetDefaultTabStack();
						DefaultTabStack == EDefaultDashboardTabStack::Log 
						|| DefaultTabStack == EDefaultDashboardTabStack::AudioMeters
						|| DefaultTabStack == EDefaultDashboardTabStack::Plots)
					{
						MenuBuilder.AddMenuSeparator();
					}
				}

				MenuBuilder.AddMenuSeparator();

				MenuBuilder.AddMenuEntry(
					ViewResetLayoutText,
					FText::GetEmpty(), 
					FSlateIcon(),
					FUIAction(FExecuteAction::CreateLambda([this]()
					{
						if (DashboardTabManager)
						{
							for (const auto& KVP : DashboardViewFactories)
							{
								// Try and get the dashboard tab:
								TSharedPtr<SDockTab> DashboardTab = DashboardTabManager->FindExistingLiveTab(KVP.Key);
								if (!DashboardTab.IsValid())
								{
									DashboardTab = DashboardTabManager->TryInvokeTab(KVP.Key);
								}

								if (DashboardTab.IsValid())
								{
									if (TSharedPtr<FTabManager> SubTabManager = FGlobalTabmanager::Get()->GetTabManagerForMajorTab(DashboardTab))
									{
										// There is a sub tab manager for this dashbaord tab; clear its persisted areas:
										SubTabManager->CloseAllAreas();
										SubTabManager->SavePersistentLayout();
									}
								}
							}

							if (TSharedPtr<SDockTab> OwnerTab = DashboardTabManager->GetOwnerTab())
							{
								// Wipe all the persisted areas and close tab
								DashboardTabManager->CloseAllAreas();

								bIsLayoutReseting = true;

								OwnerTab->RequestCloseTab();

								// Can't invoke the tab immediately (it won't show up), needs to be done a bit later
								AsyncTask(ENamedThreads::GameThread, [AudioInsightsTabId = OwnerTab->GetLayoutIdentifier(), &bIsLayoutReseting = this->bIsLayoutReseting]()
								{
									FGlobalTabmanager::Get()->TryInvokeTab(AudioInsightsTabId);
									bIsLayoutReseting = false;
								});
							}
						}
					}),
					FCanExecuteAction()));
			}),
			"View"
		);

		return MenuBarBuilder.MakeWidget();
	}

	TSharedRef<SWidget> FEditorDashboardFactory::MakeMainToolbarWidget()
	{
		using namespace EditorDashboardFactoryPrivate;

		static FSlateBrush BackgroundColorBrush;
		BackgroundColorBrush.TintColor = FSlateColor(FLinearColor(0.018f, 0.018f, 0.018f, 1.0f));
		BackgroundColorBrush.DrawAs = ESlateBrushDrawType::Box;

		return SNew(SBorder)
			.BorderImage(&BackgroundColorBrush)
			[
				SNew(SHorizontalBox)
				// Monitoring button
				+ SHorizontalBox::Slot()
				.HAlign(HAlign_Left)
				.VAlign(VAlign_Center)
				.AutoWidth()
				.Padding(3.0f, 0.0f, 5.0f, 0.0f)
				[
					MakeTraceModeButton(ETraceMode::Monitoring)
				]
				// Separator
				+ SHorizontalBox::Slot()
				.HAlign(HAlign_Left)
				.VAlign(VAlign_Center)
				.AutoWidth()
				.Padding(0.0f, 0.0f, 0.0f, 0.0f)
				[
					SNew(SBox)
					.HeightOverride(38.0f)
					[
						SNew(SSeparator)
						.Orientation(Orient_Vertical)
						.Thickness(2.0f)
					]
				]
				// Recording button
				+ SHorizontalBox::Slot()
				.HAlign(HAlign_Left)
				.VAlign(VAlign_Center)
				.AutoWidth()
				.Padding(5.0f, 0.0f, 5.0f, 0.0f)
				[
					MakeTraceModeButton(ETraceMode::Recording)
				]
				// Separator
				+ SHorizontalBox::Slot()
				.HAlign(HAlign_Left)
				.VAlign(VAlign_Center)
				.AutoWidth()
				.Padding(0.0f, 0.0f, 0.0f, 0.0f)
				[
					SNew(SBox)
					.HeightOverride(38.0f)
					[
						SNew(SSeparator)
						.Orientation(Orient_Vertical)
						.Thickness(2.0f)
					]
				]
				// Save snapshot button
				+ SHorizontalBox::Slot()
				.HAlign(HAlign_Left)
				.VAlign(VAlign_Center)
				.AutoWidth()
				.Padding(12.0f, 0.0f, 0.0f, 0.0f)
				[
					SNew(SButton)
					.ButtonStyle(&FAppStyle::Get().GetWidgetStyle<FButtonStyle>("SimpleButton"))
					.ToolTipText(SaveSnapshotTooltipText)
					.IsEnabled_Lambda([this]()
					{
						IAudioInsightsTraceModule& TraceModule = FAudioInsightsEditorModule::GetChecked().GetTraceModule();
						return TraceModule.IsTraceAnalysisActive();
					})
					.OnClicked_Lambda([]()
					{
						// Save snapshot
						IAudioInsightsTraceModule& TraceModule = FAudioInsightsEditorModule::GetChecked().GetTraceModule();
						TraceModule.SaveTraceSnapshot();

						ShowNotification(SaveSnapshotNotificationText, SaveSnapshotNotificationSubText);

						return FReply::Handled();
					})
					[
						SNew(SBox)
						.HeightOverride(16.0f)
						[
							SNew(SHorizontalBox)
							// Trace snapshot icon
							+ SHorizontalBox::Slot()
							.VAlign(VAlign_Center)
							.AutoWidth()
							[
								SNew(SImage)
								.Image(FSlateStyle::Get().GetBrush("AudioInsights.Icon.Trace.Snapshot"))
								.ColorAndOpacity(FSlateColor::UseForeground())
							]
						]
					]
				]
				// Trace Bookmark Button
				+ SHorizontalBox::Slot()
				.HAlign(HAlign_Left)
				.VAlign(VAlign_Center)
				.AutoWidth()
				.Padding(5.0f, 0.0f, 10.0f, 0.0f)
				[
					SNew(SButton)
					.ButtonStyle(&FAppStyle::Get().GetWidgetStyle<FButtonStyle>("SimpleButton"))
					.ToolTipText(SaveBookmarkTooltipText)
					.IsEnabled_Lambda([this]()
					{
						IAudioInsightsTraceModule& TraceModule = FAudioInsightsEditorModule::GetChecked().GetTraceModule();
						return TraceModule.IsTraceAnalysisActive();
					})
					.OnClicked_Lambda([this]()
					{
						CreateTraceBookmark();

						return FReply::Handled();
					})
					[
						SNew(SBox)
						.HeightOverride(16.0f)
						[
							SNew(SHorizontalBox)
							// Save Bookmark icon
							+ SHorizontalBox::Slot()
							.VAlign(VAlign_Center)
							.AutoWidth()
							[
								SNew(SImage)
								.Image(FSlateStyle::Get().GetBrush("AudioInsights.Icon.Trace.Bookmark"))
								.ColorAndOpacity(FSlateColor::UseForeground())
							]
						]
					]
				]
				// Separator
				+ SHorizontalBox::Slot()
				.HAlign(HAlign_Left)
				.VAlign(VAlign_Center)
				.AutoWidth()
				.Padding(0.0f, 0.0f, 0.0f, 0.0f)
				[
					SNew(SBox)
					.HeightOverride(38.0f)
					[
						SNew(SSeparator)
						.Orientation(Orient_Vertical)
						.Thickness(2.0f)
					]
				]
				// Only trace audio channels icon
				+ SHorizontalBox::Slot()
				.AutoWidth()
				.VAlign(VAlign_Center)
				.Padding(20.0f, 0.0f, 0.0f, 0.0f)
				[
					SNew(SImage)
					.Image(FSlateStyle::Get().GetBrush("AudioInsights.Icon.OnlyTraceAudioChannels"))
					.ToolTipText(OnlyTraceAudioChannelsTooltipText)
				]
				// Only trace audio channels checkbox
				+ SHorizontalBox::Slot()
				.HAlign(HAlign_Left)
				.VAlign(VAlign_Center)
				.AutoWidth()
				.Padding(8.0f, 0.0f, 18.0f, 0.0f)
				[
					SNew(SCheckBox)
					.ToolTipText(OnlyTraceAudioChannelsTooltipText)
					.IsChecked_Lambda([this]() { return bOnlyTraceAudioChannels ? ECheckBoxState::Checked : ECheckBoxState::Unchecked; })
					.OnCheckStateChanged_Lambda([this](ECheckBoxState NewState) 
					{ 
						bOnlyTraceAudioChannels = NewState == ECheckBoxState::Checked;

						IAudioInsightsTraceModule& TraceModule = FAudioInsightsEditorModule::GetChecked().GetTraceModule();
						TraceModule.OnOnlyTraceAudioChannelsStateChanged(bOnlyTraceAudioChannels);
					})
				]
				// Separator
				+ SHorizontalBox::Slot()
				.HAlign(HAlign_Left)
				.VAlign(VAlign_Center)
				.AutoWidth()
				.Padding(0.0f, 0.0f, 0.0f, 0.0f)
				[
					SNew(SBox)
					.HeightOverride(38.0f)
					[
						SNew(SSeparator)
						.Orientation(Orient_Vertical)
						.Thickness(2.0f)
					]
				]
				// World filter label
				+ SHorizontalBox::Slot()
				.HAlign(HAlign_Right)
				.VAlign(VAlign_Center)
				.Padding(2.0f, 0.0f)
				[
					SNew(STextBlock)
					.Text(WorldFilterText)
					.ToolTipText(WorldFilterTooltipText)
					.Font(IPropertyTypeCustomizationUtils::GetRegularFont())
				]
				// World filter combobox
				+ SHorizontalBox::Slot()
				.HAlign(HAlign_Left)
				.VAlign(VAlign_Center)
				.AutoWidth()
				.Padding(2.0f, 0.0f)
				[
					SAssignNew(AudioDeviceComboBox, SComboBox<TSharedPtr<::Audio::FDeviceId>>)
					.ToolTipText(WorldFilterTooltipText)
					.OptionsSource(&AudioDeviceIds)
					.OnGenerateWidget_Lambda([](const TSharedPtr<::Audio::FDeviceId>& WidgetDeviceId)
					{
						FText NameText = GetDebugNameFromDeviceId(*WidgetDeviceId);
						return SNew(STextBlock)
							.Text(NameText)
							.Font(IPropertyTypeCustomizationUtils::GetRegularFont());
					})
					.OnSelectionChanged_Lambda([this](TSharedPtr<::Audio::FDeviceId> NewDeviceId, ESelectInfo::Type)
					{
						if (NewDeviceId.IsValid())
						{
							ActiveDeviceId = *NewDeviceId;
							RefreshDeviceSelector();

							OnActiveAudioDeviceChanged.Broadcast();
						}
					})
					[
						SNew(STextBlock)
						.Font(IPropertyTypeCustomizationUtils::GetRegularFont())
						.Text_Lambda([this]()
						{
							return GetDebugNameFromDeviceId(ActiveDeviceId);
						})
					]
				]
			];
	}

	TSharedRef<SWidget> FEditorDashboardFactory::MakeTraceModeButton(const ETraceMode InTraceButtonMode)
	{
		using namespace EditorDashboardFactoryPrivate;

		return SNew(SBox)
			.WidthOverride(130.0f)
			.HAlign(HAlign_Center)
			.VAlign(VAlign_Center)
			[
				SNew(SButton)
				.ButtonStyle(&FAppStyle::Get().GetWidgetStyle<FButtonStyle>("SimpleButton"))
				.ToolTipText_Lambda([InTraceButtonMode]()
				{
					const IAudioInsightsTraceModule& TraceModule = FAudioInsightsEditorModule::GetChecked().GetTraceModule();

					const ETraceMode CurrentTraceMode = TraceModule.GetTraceMode();
					const bool bIsButtonActive = InTraceButtonMode == ETraceMode::Monitoring ? CurrentTraceMode != ETraceMode::None : CurrentTraceMode == InTraceButtonMode;
					
					if (TraceModule.IsTraceAnalysisActive() && bIsButtonActive)
					{
						return InTraceButtonMode == ETraceMode::Monitoring ? StopMonitoringTooltipText : StopRecordingTooltipText;
					}

					return InTraceButtonMode == ETraceMode::Monitoring ? StartMonitoringTooltipText : StartRecordingTooltipText;
				})
				.OnClicked_Lambda([this, InTraceButtonMode]()
				{
					IAudioInsightsTraceModule& TraceModule = FAudioInsightsEditorModule::GetChecked().GetTraceModule();

					if (FTraceAuxiliary::IsConnected())
					{
						const ETraceMode TraceMode = TraceModule.GetTraceMode();

						TraceModule.StopTraceAnalysis();

						// Go to Recording mode when Monitoring is active and Record button is pressed
						if (InTraceButtonMode == ETraceMode::Recording)
						{
							// Stopping a trace doesn't occur immediately, we need to check until it actually
							// stops in order to call StartTraceAnalysis again (and disable the ticker)
							auto StartTraceAnalysisDeferred = [](const bool bInOnlyTraceAudioChannels, const ETraceMode InTraceMode)
							{
								FTSTicker::GetCoreTicker().AddTicker(FTickerDelegate::CreateLambda(
									[bInOnlyTraceAudioChannels, InTraceMode](float DeltaTime)
									{
										if (FTraceAuxiliary::IsConnected())
										{
											return true;
										}

										IAudioInsightsTraceModule& TraceModule = FAudioInsightsEditorModule::GetChecked().GetTraceModule();
										TraceModule.StartTraceAnalysis(bInOnlyTraceAudioChannels, InTraceMode);
										ShowRecordingNotification();

										return false;
									}));
							};

							if (TraceMode == ETraceMode::Monitoring)
							{
								StartTraceAnalysisDeferred(bOnlyTraceAudioChannels, ETraceMode::Recording);
							}
						}
					}
					else
					{
						TraceModule.StartTraceAnalysis(bOnlyTraceAudioChannels, InTraceButtonMode);

						if (InTraceButtonMode == ETraceMode::Recording)
						{
							ShowRecordingNotification();
						}
					}

					return FReply::Handled();
				})
				[
					SNew(SBox)
					.HeightOverride(16.0f)
					[
						SNew(SHorizontalBox)
						// Trace button icon
						+ SHorizontalBox::Slot()
						.VAlign(VAlign_Center)
						.AutoWidth()
						[
							SNew(SImage)
							.Image(FSlateStyle::Get().GetBrush("AudioInsights.Icon.Trace"))
							.ColorAndOpacity_Lambda([InTraceButtonMode]()
				 			{
								const IAudioInsightsTraceModule& TraceModule = FAudioInsightsEditorModule::GetChecked().GetTraceModule();

								const ETraceMode CurrentTraceMode = TraceModule.GetTraceMode();
								const bool bIsButtonActive = InTraceButtonMode == ETraceMode::Monitoring ? CurrentTraceMode != ETraceMode::None : CurrentTraceMode == InTraceButtonMode;

								if (TraceModule.IsTraceAnalysisActive() && bIsButtonActive)
								{
									return FSlateColor(InTraceButtonMode == ETraceMode::Monitoring ? FLinearColor::Green : FLinearColor::Red);
								}

								return FSlateColor::UseForeground();
				 			})
						]
						// Trace button text
						+ SHorizontalBox::Slot()
						.VAlign(VAlign_Center)
						.AutoWidth()
						.Padding(6.0f, 1.0f, 0.0f, 0.0f)
						[
							SNew(STextBlock)
							.Justification(ETextJustify::Center)
							.Text_Lambda([InTraceButtonMode]()
				 			{
								const IAudioInsightsTraceModule& TraceModule = FAudioInsightsEditorModule::GetChecked().GetTraceModule();

								const ETraceMode CurrentTraceMode = TraceModule.GetTraceMode();
								const bool bIsButtonActive = InTraceButtonMode == ETraceMode::Monitoring ? CurrentTraceMode != ETraceMode::None	: CurrentTraceMode == InTraceButtonMode;

								if (TraceModule.IsTraceAnalysisActive() && bIsButtonActive)
								{
									return InTraceButtonMode == ETraceMode::Monitoring ? StopMonitoringText : StopRecordingText;
								}

								return InTraceButtonMode == ETraceMode::Monitoring ? StartMonitoringText : StartRecordingText;
				 			})
							.Font(IPropertyTypeCustomizationUtils::GetRegularFont())
						]
					]
				]
			];
	}

	void FEditorDashboardFactory::SetActiveDeviceId(const ::Audio::FDeviceId InDeviceId)
	{
		const TObjectPtr<const UAudioInsightsEditorSettings> AudioInsightsEditorSettings = GetDefault<UAudioInsightsEditorSettings>();

		// We don't want to set ActiveDeviceId if bWorldFilterDefaultsToFirstClient is true and more than 2 PIE clients are running
		if (AudioInsightsEditorSettings == nullptr ||
			(AudioInsightsEditorSettings && !AudioInsightsEditorSettings->bWorldFilterDefaultsToFirstClient) ||
			AudioDeviceIds.Num() < 2)
		{
			ActiveDeviceId = InDeviceId;
		}
	}

	void FEditorDashboardFactory::InitDelegates()
	{
		if (!OnWorldRegisteredToAudioDeviceHandle.IsValid())
		{
			OnWorldRegisteredToAudioDeviceHandle = FAudioDeviceWorldDelegates::OnWorldRegisteredToAudioDevice.AddSP(this, &FEditorDashboardFactory::OnWorldRegisteredToAudioDevice);
		}

		if (!OnWorldUnregisteredFromAudioDeviceHandle.IsValid())
		{
			OnWorldUnregisteredFromAudioDeviceHandle = FAudioDeviceWorldDelegates::OnWorldUnregisteredWithAudioDevice.AddSP(this, &FEditorDashboardFactory::OnWorldUnregisteredFromAudioDevice);
		}

		if (!OnDeviceCreatedHandle.IsValid())
		{
			OnDeviceCreatedHandle = FAudioDeviceManagerDelegates::OnAudioDeviceCreated.AddSP(this, &FEditorDashboardFactory::OnDeviceCreated);
		}

		if (!OnDeviceDestroyedHandle.IsValid())
		{
			OnDeviceDestroyedHandle = FAudioDeviceManagerDelegates::OnAudioDeviceDestroyed.AddSP(this, &FEditorDashboardFactory::OnDeviceDestroyed);
		}

		if (!OnTraceStartedHandle.IsValid())
		{
			OnTraceStartedHandle = FTraceAuxiliary::OnTraceStarted.AddSP(this, &FEditorDashboardFactory::OnTraceStarted);
		}
	}

	TSharedRef<FTabManager::FLayout> FEditorDashboardFactory::GetDefaultTabLayout()
	{
		using namespace EditorDashboardFactoryPrivate;

		TSharedRef<FTabManager::FStack> ViewportTabStack = FTabManager::NewStack();
		TSharedRef<FTabManager::FStack> LogTabStack = FTabManager::NewStack();
		TSharedRef<FTabManager::FStack> AnalysisTabStack = FTabManager::NewStack();
		TSharedRef<FTabManager::FStack> AudioMetersTabStack = FTabManager::NewStack();
		TSharedRef<FTabManager::FStack> PlotsTabStack = FTabManager::NewStack();
		TSharedRef<FTabManager::FStack> AudioAnalyzerRackTabStack = FTabManager::NewStack()->SetHideTabWell(true)->SetSizeCoefficient(0.15f);

		for (const auto& KVP : DashboardViewFactories)
		{
			const FName& FactoryName = KVP.Key;
			const TSharedPtr<IDashboardViewFactory>& Factory = KVP.Value;

			const EDefaultDashboardTabStack DefaultTabStack = Factory->GetDefaultTabStack();
			switch (DefaultTabStack)
			{
				case EDefaultDashboardTabStack::Viewport:
				{
					ViewportTabStack->AddTab(FactoryName, ETabState::OpenedTab);
				}
				break;

				case EDefaultDashboardTabStack::Log:
				{
					LogTabStack->AddTab(FactoryName, ETabState::OpenedTab);
				}
				break;

				case EDefaultDashboardTabStack::Analysis:
				{
					AnalysisTabStack->AddTab(FactoryName, ETabState::OpenedTab);
				}
				break;

				case EDefaultDashboardTabStack::AudioMeters:
				{
					AudioMetersTabStack->AddTab(FactoryName, ETabState::OpenedTab);
				}
				break;

				case EDefaultDashboardTabStack::Plots:
				{
					PlotsTabStack->AddTab(FactoryName, ETabState::OpenedTab);
				}
				break;

				case EDefaultDashboardTabStack::AudioAnalyzerRack:
				{
					AudioAnalyzerRackTabStack->AddTab(FactoryName, ETabState::OpenedTab);
				}
				break;

				default:
					break;
			}
		}

		AnalysisTabStack->SetForegroundTab(FName("Sounds"));

		return FTabManager::NewLayout("AudioDashboard_Editor_Layout_v2")
		->AddArea
		(
			FTabManager::NewPrimaryArea()
			->SetOrientation(Orient_Vertical)
			->Split
			(
				// Left column
				FTabManager::NewSplitter()
				->SetOrientation(Orient_Horizontal)
				->Split
				(
					// Top
					FTabManager::NewSplitter()
					->SetOrientation(Orient_Vertical)
					->SetSizeCoefficient(0.25f) // Column width
					->Split
					(
						ViewportTabStack
						->SetSizeCoefficient(0.5f)
					)
					// Bottom
					->Split
					(
						LogTabStack
						->SetSizeCoefficient(0.5f)
					)
				)
				
				// Middle column
				->Split
				(
					// Top
					FTabManager::NewSplitter()
					->SetOrientation(Orient_Vertical)
					->SetSizeCoefficient(0.6f) // Column width
					->Split
					(
						FTabManager::NewSplitter()
						->SetOrientation(Orient_Horizontal)
						->Split
						(
							AnalysisTabStack
							->SetSizeCoefficient(0.58f)
						)
					)
					// Bottom
					->Split
					(
						// Top
						FTabManager::NewSplitter()
						->SetOrientation(Orient_Horizontal)
						->SetSizeCoefficient(0.42f) // Row width
						->Split
						(
							PlotsTabStack
							->SetSizeCoefficient(0.5f)
						)
						// Bottom
						->Split
						(
							AudioMetersTabStack
							->SetSizeCoefficient(0.5f)
						)
					)
				)
				// Right column
				->Split
				(
					AudioAnalyzerRackTabStack
				)
			)
		);
	}

	void FEditorDashboardFactory::RegisterTabSpawners()
	{
		using namespace EditorDashboardFactoryPrivate;

		DashboardWorkspace = DashboardTabManager->AddLocalWorkspaceMenuCategory(ToolNameText);

		for (const auto& KVP : DashboardViewFactories)
		{
			const FName& FactoryName = KVP.Key;
			const TSharedPtr<IDashboardViewFactory>& Factory = KVP.Value;

			DashboardTabManager->RegisterTabSpawner(FactoryName, FOnSpawnTab::CreateLambda([this, Factory](const FSpawnTabArgs& Args)
			{
				TSharedRef<SDockTab> DockTab = SNew(SDockTab)
					.Clipping(EWidgetClipping::ClipToBounds)
					.Label(Factory->GetDisplayName());

				TSharedRef<SWidget> DashboardView = Factory->MakeWidget(DockTab, Args);
				DockTab->SetContent(DashboardView);

				return DockTab;
			}))
			.SetDisplayName(Factory->GetDisplayName())
			.SetGroup(DashboardWorkspace->AsShared())
			.SetIcon(Factory->GetIcon());
		}
	}

	void FEditorDashboardFactory::UnregisterTabSpawners()
	{
		if (DashboardTabManager.IsValid())
		{
			for (const auto& KVP : DashboardViewFactories)
			{
				const FName& FactoryName = KVP.Key;
				DashboardTabManager->UnregisterTabSpawner(FactoryName);
			}
		}
	}

	void FEditorDashboardFactory::RegisterViewFactory(TSharedRef<IDashboardViewFactory> InFactory)
	{
		if (const FName Name = InFactory->GetName(); 
			ensureAlwaysMsgf(!DashboardViewFactories.Contains(Name), TEXT("Failed to register Audio Insights Dashboard '%s': Dashboard with name already registered"), *Name.ToString()))
		{
			DashboardViewFactories.Add(Name, InFactory);
		}
	}

	void FEditorDashboardFactory::UnregisterViewFactory(FName InName)
	{
		DashboardViewFactories.Remove(InName);
	}

	TSharedRef<FTabManager::FLayout> FEditorDashboardFactory::LoadLayoutFromConfig()
	{
		return FLayoutSaveRestore::LoadFromConfig(GEditorLayoutIni, GetDefaultTabLayout());
	}

	void FEditorDashboardFactory::SaveLayoutToConfig()
	{
		if (DashboardTabManager.IsValid())
		{
			FLayoutSaveRestore::SaveToConfig(GEditorLayoutIni, DashboardTabManager->PersistLayout());
		}
	}
} // namespace UE::Audio::Insights

#undef LOCTEXT_NAMESPACE
