// Copyright Epic Games, Inc. All Rights Reserved.

float3	SpriteFacingAndAlignment_SpriteFacing;
float3	SpriteFacingAndAlignment_SpriteAlignment;

void SpriteFacingAndAlignment_Simulate(inout FStatelessParticle Particle)
{
	Particle.SpriteFacing = SpriteFacingAndAlignment_SpriteFacing;
	Particle.SpriteAlignment = SpriteFacingAndAlignment_SpriteAlignment;

	Particle.PreviousSpriteFacing = SpriteFacingAndAlignment_SpriteFacing;
	Particle.PreviousSpriteAlignment = SpriteFacingAndAlignment_SpriteAlignment;
}
